(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'),ctx=canvas.getContext('2d'),bc=$('#battleCanvas'),bctx=bc.getContext('2d');
const KEY='sharkquest-v65';
const sharks=[
{id:'reef',name:'Requin de récif',rare:'Commun',mood:'Curieux',base:.68,power:6,speed:.8,color:'#78949d',pool:['lagoon']},
{id:'hammer',name:'Requin marteau',rare:'Peu commun',mood:'Méfiant',base:.56,power:8,speed:1.05,color:'#78878b',pool:['lagoon','deep']},
{id:'tiger',name:'Requin tigre',rare:'Peu commun',mood:'Agressif',base:.46,power:12,speed:.95,color:'#89755d',pool:['lagoon']},
{id:'mako',name:'Requin mako',rare:'Rare',mood:'Très rapide',base:.37,power:11,speed:1.35,color:'#537c8e',pool:['deep']},
{id:'white',name:'Grand requin blanc',rare:'Rare',mood:'Prédateur',base:.30,power:15,speed:1,color:'#93a2a7',pool:['deep']},
{id:'whale',name:'Requin-baleine',rare:'Très rare',mood:'Paisible',base:.52,power:4,speed:.55,color:'#466d79',pool:['deep']},
{id:'meg',name:'Mégalodon',rare:'Légendaire',mood:'Boss',base:.11,power:22,speed:.9,color:'#38494e',pool:['boss']}
];
let S={char:null,hp:100,balls:8,x:560,y:1160,caught:{},seen:{}};try{Object.assign(S,JSON.parse(localStorage.getItem(KEY))||{})}catch{}
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const W={w:2600,h:1800,vw:innerWidth,vh:innerHeight,t:0,last:performance.now(),camX:0,camY:0,keys:{},touch:{},dir:'down',moving:false,dog:{x:505,y:1200},battle:null,fin:null,nextFin:0,atlas:new Image()};W.atlas.src='assets/visuals.webp';
const zones=[{name:'Lagon turquoise',type:'lagoon',x:420,y:410,w:570,h:345,pool:['reef','reef','hammer','tiger']},{name:'Lagon nord',type:'deep',x:1530,y:350,w:620,h:375,pool:['hammer','mako','white','whale']},{name:'Lagon des roseaux',type:'lagoon',x:820,y:1020,w:800,h:325,pool:['reef','tiger','hammer','white']},{name:'Ponton abandonné',type:'deep',x:2040,y:700,w:370,h:245,pool:['hammer','mako','white']}],camp={x:290,y:1260,w:350,h:235};
function fit(){const d=Math.min(devicePixelRatio||1,2);for(const c of [canvas,bc]){c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high'}W.vw=innerWidth;W.vh=innerHeight}addEventListener('resize',fit);fit();
W.atlas.onload=()=>$('#loading').classList.add('hidden');W.atlas.onerror=()=>$('#loading').textContent='Erreur de chargement des visuels.';
const rr=(c,x,y,w,h,r,col)=>{c.fillStyle=col;c.beginPath();c.roundRect(x,y,w,h,r);c.fill()};
function setPortrait(el,char){el.classList.remove('justine','guillaume');el.classList.add(char==='Guillaume'?'guillaume':'justine')}
function refresh(){const n=Object.keys(S.caught).length;setPortrait($('#hudPortrait'),S.char||'Justine');setPortrait($('#battlePortrait'),S.char||'Justine');$('#hudName').textContent=S.char||'Justine';$('#battleName').textContent=(S.char||'Justine')+' + Syrachi';$('#hp').textContent=S.hp;$('#hpBar').style.width=S.hp+'%';$('#balls').textContent=S.balls;$('#count').textContent=n;$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;$('#quest').textContent=n<3?`Découvrir 3 espèces (${n}/3).`:n<5?`Trouver 5 espèces (${n}/5).`:n<7?`Le Mégalodon peut apparaître (${n}/7).`:'SharkDex complet : 7/7.'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast._);toast._=setTimeout(()=>e.classList.remove('show'),1600)}
$$('.char-card').forEach(b=>b.onclick=()=>{S.char=b.dataset.char;$$('.char-card').forEach(x=>x.classList.toggle('selected',x===b));$('#playBtn').disabled=false;$('#playBtn').textContent='Commencer avec '+S.char;save()});
function enter(reset){if(!S.char)return;if(reset)S={char:S.char,hp:100,balls:8,x:560,y:1160,caught:{},seen:{}};$('#start').classList.add('hidden');$('#game').classList.remove('hidden');W.dog={x:S.x-55,y:S.y+40};refresh();save();drawWorld()}
$('#playBtn').onclick=()=>enter(true);if(S.char){const b=$(`.char-card[data-char="${S.char}"]`);if(b)b.classList.add('selected');$('#playBtn').disabled=false;$('#playBtn').textContent='Nouvelle partie avec '+S.char;$('#resumeBtn').classList.remove('hidden');$('#resumeBtn').onclick=()=>enter(false)}
function palm(c,x,y,s){c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#65462d';c.lineWidth=8;c.beginPath();c.moveTo(0,32);c.quadraticCurveTo(3,-18,-5,-56);c.stroke();c.fillStyle='#3e7b46';for(let i=0;i<6;i++){c.save();c.rotate(i*Math.PI/3+Math.sin(W.t+x)*.03);c.beginPath();c.ellipse(20,-56,34,8,-.4,0,Math.PI*2);c.fill();c.restore()}c.restore()}
function water(c,z){rr(c,z.x,z.y,z.w,z.h,86,'#48b5c3');c.strokeStyle='#fff5';c.lineWidth=2;for(let y=z.y+26;y<z.y+z.h;y+=46)for(let x=z.x+20;x<z.x+z.w;x+=82){c.beginPath();c.ellipse(x+Math.sin(W.t*2+y)*6,y,25,6,0,0,Math.PI*2);c.stroke()}}
function drawAvatar(c,char,x,y,dog=false){if(!W.atlas.complete)return;let sx=char==='Guillaume'?300:char==='Syrachi'?600:0,sy=0,sw=300,sh=375;let w=dog?42:50,h=dog?52:64;let bob=Math.sin(W.t*9)*(W.moving?2:0);c.save();c.translate(x,y+bob);c.fillStyle='#0005';c.beginPath();c.ellipse(0,h*.48,w*.42,8,0,0,Math.PI*2);c.fill();c.beginPath();c.roundRect(-w/2,-h*.72,w,h,12);c.clip();c.drawImage(W.atlas,sx,sy,sw,sh,-w/2,-h*.72,w,h);c.restore();if(!dog){c.strokeStyle=char==='Guillaume'?'#69dbe0dd':'#f1c66ddd';c.lineWidth=3;c.beginPath();c.arc(x,y+4,31,0,Math.PI*2);c.stroke()}}
function zoneName(){if(S.x>camp.x-40&&S.x<camp.x+camp.w+40&&S.y>camp.y-40&&S.y<camp.y+camp.h+40)return'Camp de base';let z=zones.find(z=>S.x>z.x-90&&S.x<z.x+z.w+90&&S.y>z.y-90&&S.y<z.y+z.h+90);if(z)return z.name;if(S.y<420)return'Plage des Palmes';return S.x>1850?'Côte Est':'Jungle intérieure'}
function blocked(x,y){if(x<150||y<150||x>2450||y>1620)return true;if(zones.slice(0,3).some(z=>x>z.x+35&&x<z.x+z.w-35&&y>z.y+35&&y<z.y+z.h-35))return true;return false}
function drawWorld(){const c=ctx;c.clearRect(0,0,W.vw,W.vh);W.camX=Math.max(0,Math.min(W.w-W.vw,S.x-W.vw/2));W.camY=Math.max(0,Math.min(W.h-W.vh,S.y-W.vh/2));c.save();c.translate(-W.camX,-W.camY);c.fillStyle='#2f97a7';c.fillRect(0,0,W.w,W.h);rr(c,120,105,2360,1580,210,'#e6c97f');rr(c,270,280,2050,1210,165,'#5b9852');rr(c,340,345,1910,1080,130,'#79b261');rr(c,500,1260,1530,120,48,'#d3b26f');rr(c,1170,690,130,640,48,'#d3b26f');rr(c,770,310,1210,92,36,'#d3b26f');zones.forEach(z=>water(c,z));rr(c,camp.x,camp.y,camp.w,camp.h,28,'#745239');c.fillStyle='#bd584a';c.beginPath();c.moveTo(camp.x-25,camp.y+30);c.lineTo(camp.x+camp.w/2,camp.y-105);c.lineTo(camp.x+camp.w+25,camp.y+30);c.fill();rr(c,camp.x+140,camp.y+105,62,128,8,'#3d2d25');c.fillStyle='#735039';c.fillRect(2030,715,430,90);for(let i=0;i<9;i++)c.fillRect(2040+i*48,670,18,175);for(let i=0;i<28;i++){let x=360+(i*191)%1800,y=390+(i*137)%980;if(zones.some(z=>x>z.x-70&&x<z.x+z.w+70&&y>z.y-70&&y<z.y+z.h+70))continue;palm(c,x,y,.8+(i%4)*.08)}c.fillStyle='#17343b';c.font='800 14px system-ui';zones.forEach(z=>c.fillText(z.name.toUpperCase(),z.x+18,z.y-14));c.fillText('CAMP DE BASE',camp.x+18,camp.y+camp.h+28);if(W.fin){c.save();c.translate(W.fin.x,W.fin.y);c.scale(1+Math.sin(W.t*6)*.12,1);c.fillStyle='#233d43';c.beginPath();c.moveTo(-14,12);c.quadraticCurveTo(0,-38,18,12);c.closePath();c.fill();c.restore()}drawAvatar(c,'Syrachi',W.dog.x,W.dog.y,true);drawAvatar(c,S.char||'Justine',S.x,S.y,false);c.restore();$('#zoneLabel').textContent=zoneName().toUpperCase()}
function choose(z){let id=z.pool[Math.floor(Math.random()*z.pool.length)];if(Object.keys(S.caught).length>=5&&Math.random()<.07)id='meg';return sharks.find(s=>s.id===id)}
function spawnFin(){const z=zones[Math.floor(Math.random()*zones.length)],sp=choose(z);W.fin={x:z.x+80+Math.random()*(z.w-160),y:z.y+80+Math.random()*(z.h-160),z,sp,life:11000};W.nextFin=performance.now()+8000+Math.random()*6000}
function update(dt){if($('#game').classList.contains('hidden')||W.battle)return;W.t+=dt;let dx=0,dy=0;if(W.keys.ArrowLeft||W.keys.a||W.touch.left)dx--;if(W.keys.ArrowRight||W.keys.d||W.touch.right)dx++;if(W.keys.ArrowUp||W.keys.w||W.touch.up)dy--;if(W.keys.ArrowDown||W.keys.s||W.touch.down)dy++;if(dx&&dy){dx*=.707;dy*=.707}W.moving=!!(dx||dy);const nx=S.x+dx*250*dt,ny=S.y+dy*250*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;W.dog.x+=(S.x-55-W.dog.x)*Math.min(1,dt*5);W.dog.y+=(S.y+40-W.dog.y)*Math.min(1,dt*5);if(!W.fin&&performance.now()>W.nextFin)spawnFin();if(W.fin){W.fin.life-=dt*1000;if(W.fin.life<0){W.fin=null;W.nextFin=performance.now()+3500}else if(Math.hypot(S.x-W.fin.x,S.y-W.fin.y)<110){const f=W.fin;W.fin=null;startBattle(f.sp,f.z)}}let z=zones.find(z=>S.x>z.x-115&&S.x<z.x+z.w+115&&S.y>z.y-115&&S.y<z.y+z.h+115);if(z&&W.moving&&Math.random()<dt*.05)startBattle(choose(z),z);if(zoneName()==='Camp de base'&&(S.hp<100||S.balls<8)){S.hp=100;S.balls=Math.max(S.balls,8);refresh();save();toast('Repos au camp : énergie et Pokéballs restaurées.')}drawWorld()}
function loop(t){const dt=Math.min(.035,(t-W.last)/1000);W.last=t;update(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setActions(on){['observeBtn','captureBtn','dogBtn','runBtn'].forEach(id=>$('#'+id).disabled=!on);if(W.battle?.dogUsed)$('#dogBtn').disabled=true}
function startBattle(sp,z){if(W.battle)return;W.battle={sp,z,calm:100,dogUsed:false,shield:false,start:performance.now(),attackUntil:0};S.seen[sp.id]=true;save();$('#battle').classList.remove('hidden');const bg=$('#battleBg');bg.classList.remove('justine','guillaume');bg.classList.add(S.char==='Guillaume'?'guillaume':'justine');setPortrait($('#battlePortrait'),S.char||'Justine');$('#enemyName').textContent=sp.name;$('#enemyRarity').textContent=sp.rare.toUpperCase();$('#enemyMood').textContent=sp.mood;$('#enemyPct').textContent='100';$('#enemyBar').style.width='100%';$('#battleText').textContent=sp.id==='meg'?'L’océan gronde… le Mégalodon apparaît !':`Un ${sp.name.toLowerCase()} apparaît près de ${z.name.toLowerCase()} !`;refresh();setActions(true);cancelAnimationFrame(startBattle._);drawBattle()}
function drawShark(c,x,y,sp,s,t){c.save();c.translate(x,y);c.scale(s,s);c.rotate(Math.sin(t*1.3)*.025);c.fillStyle=sp.color;c.strokeStyle='#26383d';c.lineWidth=3;c.beginPath();c.ellipse(0,0,180,60,0,0,Math.PI*2);c.fill();c.stroke();c.save();c.translate(-160,0);c.rotate(Math.sin(t*4*sp.speed)*.18);c.beginPath();c.moveTo(0,0);c.lineTo(-85,-64);c.lineTo(-64,0);c.lineTo(-85,64);c.closePath();c.fill();c.stroke();c.restore();c.beginPath();c.moveTo(-12,-50);c.lineTo(34,-126);c.lineTo(63,-42);c.closePath();c.fill();if(sp.id==='hammer'){c.fillRect(118,-54,76,28);c.beginPath();c.ellipse(156,-40,42,18,0,0,Math.PI*2);c.fill()}else{c.beginPath();c.ellipse(147,0,73,50,0,0,Math.PI*2);c.fill()}if(sp.id==='tiger'){c.strokeStyle='#443b31';c.lineWidth=7;for(let i=-75;i<90;i+=34){c.beginPath();c.moveTo(i,-44);c.lineTo(i+18,44);c.stroke()}}if(sp.id==='whale'){c.fillStyle='#daf0f2';for(let i=0;i<23;i++){c.beginPath();c.arc(-120+(i*47)%270,-36+((i*31)%72),3,0,Math.PI*2);c.fill()}}c.fillStyle='#dbe3e4';c.beginPath();c.ellipse(64,24,126,26,0,0,Math.PI*2);c.fill();c.fillStyle='#02090c';c.beginPath();c.arc(150,-16,5,0,Math.PI*2);c.fill();c.restore()}
function drawBattle(){if(!W.battle)return;const sp=W.battle.sp,t=(performance.now()-W.battle.start)/1000;bctx.clearRect(0,0,W.vw,W.vh);let x=W.vw*.72+Math.sin(t*sp.speed)*W.vw*.05,y=W.vh*.43+Math.sin(t*1.8)*10,s=Math.min(W.vw/1100,W.vh/680)*(sp.id==='meg'?1.55:sp.id==='whale'?1.3:1);if(performance.now()<W.battle.attackUntil){let q=1-(W.battle.attackUntil-performance.now())/500;s*=1+Math.sin(q*Math.PI)*.5;x-=Math.sin(q*Math.PI)*W.vw*.12}drawShark(bctx,x,y,sp,s,t);startBattle._=requestAnimationFrame(drawBattle)}
function enemyHit(){const b=W.battle;let d=b.sp.power+Math.floor(Math.random()*5);if(b.shield){d=Math.ceil(d/2);b.shield=false}S.hp=Math.max(0,S.hp-d);b.attackUntil=performance.now()+500;refresh();save();if(S.hp<=0){$('#battleText').textContent='Syrachi te ramène au camp.';setActions(false);setTimeout(()=>{S.hp=100;S.x=560;S.y=1160;closeBattle()},850);return true}return false}
$('#observeBtn').onclick=()=>{const b=W.battle;if(!b)return;setActions(false);b.calm=Math.max(5,b.calm-(18+Math.floor(Math.random()*18)));$('#enemyPct').textContent=b.calm;$('#enemyBar').style.width=b.calm+'%';$('#battleText').textContent='Tu observes ses mouvements…';setTimeout(()=>{if(b.sp.id==='whale'&&Math.random()<.6){$('#battleText').textContent='Le requin-baleine reste paisible.';setActions(true)}else if(!enemyHit()){$('#battleText').textContent='Le requin riposte !';setActions(true)}},650)};
$('#dogBtn').onclick=()=>{const b=W.battle;if(!b||b.dogUsed)return;b.dogUsed=true;b.shield=true;$('#battleText').textContent='Syrachi détourne son attention.';setActions(true)};
$('#captureBtn').onclick=()=>{const b=W.battle;if(!b)return;if(S.balls<=0){$('#battleText').textContent='Plus de Pokéballs.';return}S.balls--;refresh();setActions(false);const fx=$('#ballFx');fx.classList.remove('go');void fx.offsetWidth;fx.classList.add('go');const chance=Math.min(.94,b.sp.base+(100-b.calm)/125+(b.dogUsed?.04:0)+(b.sp.id==='whale'?.06:0));$('#battleText').textContent='Pokéball lancée…';setTimeout(()=>{if(Math.random()<chance){S.caught[b.sp.id]=(S.caught[b.sp.id]||0)+1;save();const fl=$('#flashFx');fl.classList.remove('go');void fl.offsetWidth;fl.classList.add('go');$('#battleText').textContent=`${b.sp.name} capturé !`;setTimeout(()=>{closeBattle();toast('Capture ajoutée au SharkDex !')},850)}else{$('#battleText').textContent='Il se libère !';if(!enemyHit())setActions(true)}},800)};
$('#runBtn').onclick=()=>{const b=W.battle;if(!b)return;setActions(false);if(Math.random()<(b.sp.id==='meg'?.58:.84)){setTimeout(closeBattle,420)}else{setTimeout(()=>{if(!enemyHit())setActions(true)},430)}};
function closeBattle(){cancelAnimationFrame(startBattle._);W.battle=null;$('#battle').classList.add('hidden');refresh();save();W.nextFin=performance.now()+4200}
function renderDex(){const g=$('#dexGrid');g.innerHTML='';sharks.forEach(s=>{const seen=S.seen[s.id]||S.caught[s.id],n=S.caught[s.id]||0,b=document.createElement('button');b.className='dex-card'+(seen?'':' lock');b.innerHTML=`<div class="dex-icon">${seen?'🦈':'❔'}</div><div><b>${seen?s.name:'Espèce inconnue'}</b><small>${seen?`${s.rare} • capturé x${n}`:'Non découverte'}</small></div>`;b.onclick=()=>{$('#dexIcon').textContent=seen?'🦈':'❔';$('#dexName').textContent=seen?s.name:'Espèce inconnue';$('#dexInfo').textContent=seen?`${s.rare} • ${s.mood} • capturé x${n}.`:'Explore les lagons et les côtes pour la découvrir.'};g.appendChild(b)})}
$('#dexBtn').onclick=()=>{renderDex();$('#dex').classList.remove('hidden')};$('#closeDex').onclick=()=>$('#dex').classList.add('hidden');addEventListener('keydown',e=>W.keys[e.key]=1);addEventListener('keyup',e=>W.keys[e.key]=0);$$('.dpad button').forEach(b=>{const d=b.dataset.dir;b.onpointerdown=e=>{e.preventDefault();W.touch[d]=1};b.onpointerup=b.onpointercancel=b.onpointerout=e=>{e.preventDefault();W.touch[d]=0}});refresh();
})();