(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const world=$('#world'),ctx=world.getContext('2d'),battleC=$('#battleCanvas'),bctx=battleC.getContext('2d');
const KEY='sharkquest-v64';
const A={
 j:'../v52/assets/justine.webp',g:'../v52/assets/guillaume.webp',d:'../v52/assets/syrachi.webp',
 bj:'../v52/assets/battle_justine.webp',bg:'../v52/assets/battle_guillaume.webp',wide:'../v52/battle.webp'
};
const sharks=[
 {id:'reef',name:'Requin de récif',rare:'Commun',mood:'Curieux',base:.68,pow:5,spd:.75,c:'#78949c',zones:['lagoon','beach']},
 {id:'hammer',name:'Requin marteau',rare:'Peu commun',mood:'Méfiant',base:.56,pow:8,spd:1.0,c:'#74878c',zones:['lagoon','pontoon']},
 {id:'tiger',name:'Requin tigre',rare:'Peu commun',mood:'Agressif',base:.46,pow:12,spd:.9,c:'#81745f',zones:['lagoon','beach']},
 {id:'mako',name:'Requin mako',rare:'Rare',mood:'Très rapide',base:.37,pow:11,spd:1.35,c:'#527b8e',zones:['deep','pontoon']},
 {id:'white',name:'Grand requin blanc',rare:'Rare',mood:'Prédateur',base:.3,pow:15,spd:1,c:'#87999e',zones:['deep','pontoon']},
 {id:'whale',name:'Requin-baleine',rare:'Très rare',mood:'Paisible',base:.52,pow:3,spd:.55,c:'#456c78',zones:['deep']},
 {id:'meg',name:'Mégalodon',rare:'Légendaire',mood:'Boss',base:.11,pow:22,spd:.9,c:'#34474b',zones:['boss']}
];
let S={char:null,hp:100,balls:8,x:560,y:1180,caught:{},seen:{}};try{Object.assign(S,JSON.parse(localStorage.getItem(KEY))||{})}catch{};
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const W={w:2600,h:1800,camX:0,camY:0,vw:innerWidth,vh:innerHeight,t:0,last:performance.now(),keys:{},touch:{},dir:'down',moving:false,dog:{x:S.x-58,y:S.y+38,dir:'down'},battle:null,fin:null,nextFin:0};
const lagoons=[
 {id:'turq',type:'lagoon',name:'Lagon turquoise',x:420,y:410,w:560,h:340,pool:['reef','reef','hammer','tiger']},
 {id:'north',type:'deep',name:'Lagon nord',x:1540,y:350,w:610,h:370,pool:['hammer','mako','white','whale']},
 {id:'reeds',type:'lagoon',name:'Lagon des roseaux',x:810,y:1020,w:800,h:320,pool:['reef','tiger','hammer','white']},
 {id:'pontoon',type:'pontoon',name:'Ponton abandonné',x:2040,y:690,w:370,h:250,pool:['hammer','mako','white']}
];
const camp={x:290,y:1270,w:340,h:235};
const rocks=[{x:700,y:820,r:58},{x:1260,y:760,r:52},{x:1820,y:1010,r:70},{x:690,y:1390,r:50},{x:1450,y:510,r:42}];
const portrait=n=>n==='Guillaume'?A.g:A.j;
function fit(){const d=Math.min(devicePixelRatio||1,2);for(const c of [world,battleC]){c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';c.width=innerWidth*d;c.height=innerHeight*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}W.vw=innerWidth;W.vh=innerHeight}addEventListener('resize',fit);fit();
function loadUI(){ $('#justineCardImg').src=A.j;$('#guillaumeCardImg').src=A.g;$('#syrachiCardImg').src=A.d;$('#hudDog').src=A.d; $('.start-bg').style.backgroundImage=`linear-gradient(90deg,#041118f1 0 42%,#0618209b 61%,#0004),url('${portrait(S.char||'Justine')}')`; $('#loading').style.display='none'}loadUI();
const rr=(c,x,y,w,h,r,col)=>{c.fillStyle=col;c.beginPath();c.roundRect(x,y,w,h,r);c.fill()};
function palm(c,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#61452e';c.lineWidth=9;c.beginPath();c.moveTo(0,36);c.quadraticCurveTo(3,-18,-5,-58);c.stroke();c.fillStyle='#3d7d47';for(let i=0;i<6;i++){c.save();c.rotate(i*Math.PI/3+Math.sin(W.t+x)*.035);c.beginPath();c.ellipse(21,-58,36,8,-.4,0,Math.PI*2);c.fill();c.restore()}c.restore()}
function water(c,z){rr(c,z.x,z.y,z.w,z.h,88,'#45b3c3');c.strokeStyle='#dffcff66';c.lineWidth=2;for(let yy=z.y+28;yy<z.y+z.h;yy+=45)for(let xx=z.x+25;xx<z.x+z.w;xx+=84){c.beginPath();c.ellipse(xx+Math.sin(W.t*2+yy)*7,yy,27,6,0,0,Math.PI*2);c.stroke()}}
function drawHuman(c,x,y,n,dir,moving){c.save();c.translate(x,y);let step=moving?Math.sin(W.t*11):0,bob=Math.abs(step)*2;c.translate(0,-bob);c.fillStyle='#0005';c.beginPath();c.ellipse(0,38,29,10,0,0,Math.PI*2);c.fill();
 const isJ=n==='Justine'; let flip=dir==='left'?-1:1;c.scale(flip,1);
 c.fillStyle='#5c4934';rr(c,-21,-27,42,54,10,'#5c4934');c.fillStyle='#8a6b45';rr(c,-18,-23,36,45,8,'#7b6040');
 c.strokeStyle='#403b31';c.lineWidth=13;c.lineCap='round';c.beginPath();c.moveTo(-10,20);c.lineTo(-12+step*7,49);c.moveTo(10,20);c.lineTo(12-step*7,49);c.stroke();c.strokeStyle='#2a241f';c.lineWidth=8;c.beginPath();c.moveTo(-12+step*7,49);c.lineTo(-16+step*8,57);c.moveTo(12-step*7,49);c.lineTo(16-step*8,57);c.stroke();
 rr(c,-21,-25,42,54,12,isJ?'#26292b':'#403b31');
 c.fillStyle='#7b5534';c.fillRect(-23,9,46,7);c.fillStyle='#b8894e';c.fillRect(13,12,9,14);
 c.strokeStyle='#d69d78';c.lineWidth=11;c.beginPath();c.moveTo(-18,-12);c.lineTo(-27+step*4,15);c.moveTo(18,-12);c.lineTo(27-step*4,15);c.stroke();
 c.fillStyle='#d9a27f';c.beginPath();c.arc(0,-42,17,0,Math.PI*2);c.fill();
 if(isJ){c.fillStyle='#5a3426';c.beginPath();c.arc(0,-47,20,Math.PI,Math.PI*2);c.fill();c.strokeStyle='#5a3426';c.lineWidth=8;c.beginPath();c.moveTo(-15,-47);c.quadraticCurveTo(-29,-15,-22,22);c.moveTo(15,-47);c.quadraticCurveTo(28,-14,21,20);c.stroke()}else{c.fillStyle='#211b19';c.beginPath();c.arc(0,-48,19,Math.PI,Math.PI*2);c.fill();c.fillStyle='#2b211e';c.beginPath();c.arc(0,-38,16,.1,Math.PI-.1);c.fill()}
 c.scale(flip,1);c.fillStyle='#06171ddd';rr(c,-38,-87,76,20,10,'#06171ddd');c.fillStyle='#fff';c.font='700 11px system-ui';c.textAlign='center';c.fillText(n,0,-73);c.restore()}
function drawDog(c,x,y,dir,moving){c.save();c.translate(x,y);let step=moving?Math.sin(W.t*12):0;c.fillStyle='#0004';c.beginPath();c.ellipse(0,28,27,8,0,0,Math.PI*2);c.fill();let flip=dir==='left'?-1:1;c.scale(flip,1);c.fillStyle='#11181b';c.beginPath();c.ellipse(0,0,34,23,0,0,Math.PI*2);c.fill();c.fillStyle='#f0f1ed';c.beginPath();c.ellipse(-5,0,11,20,0,0,Math.PI*2);c.fill();c.fillStyle='#11181b';c.beginPath();c.arc(25,-9,16,0,Math.PI*2);c.fill();c.fillStyle='#f0f1ed';c.beginPath();c.ellipse(29,-5,8,10,0,0,Math.PI*2);c.fill();c.fillStyle='#11181b';c.beginPath();c.moveTo(17,-20);c.lineTo(20,-36);c.lineTo(29,-22);c.fill();c.beginPath();c.moveTo(31,-22);c.lineTo(40,-35);c.lineTo(42,-17);c.fill();c.strokeStyle='#11181b';c.lineWidth=7;c.beginPath();c.moveTo(-28,-3);c.quadraticCurveTo(-48,-14,-45,-28+step*8);c.stroke();c.strokeStyle='#f0f1ed';c.lineWidth=7;c.beginPath();c.moveTo(-12,17);c.lineTo(-13+step*4,31);c.moveTo(9,17);c.lineTo(10-step*4,31);c.stroke();c.restore()}
function drawMap(){const c=ctx,VW=W.vw,VH=W.vh;c.clearRect(0,0,VW,VH);W.camX=Math.max(0,Math.min(W.w-VW,S.x-VW/2));W.camY=Math.max(0,Math.min(W.h-VH,S.y-VH/2));c.save();c.translate(-W.camX,-W.camY);c.fillStyle='#2d95a6';c.fillRect(0,0,W.w,W.h);for(let y=20;y<W.h;y+=55)for(let x=10;x<W.w;x+=90){c.strokeStyle='#fff2';c.beginPath();c.ellipse(x+Math.sin(W.t+y)*4,y,28,6,0,0,Math.PI*2);c.stroke()}
 rr(c,120,105,2360,1580,210,'#e5c77e');rr(c,270,280,2050,1210,165,'#5a9650');rr(c,340,345,1910,1080,130,'#77af5f');rr(c,500,1260,1530,120,48,'#d4b36f');rr(c,1170,690,130,640,48,'#d4b36f');rr(c,770,310,1210,92,36,'#d4b36f');lagoons.forEach(z=>water(c,z));
 rr(c,camp.x,camp.y,camp.w,camp.h,28,'#725138');c.fillStyle='#b95449';c.beginPath();c.moveTo(camp.x-25,camp.y+30);c.lineTo(camp.x+camp.w/2,camp.y-105);c.lineTo(camp.x+camp.w+25,camp.y+30);c.fill();rr(c,camp.x+138,camp.y+105,62,128,8,'#3c2d25');c.fillStyle='#735039';c.fillRect(2030,715,430,90);for(let i=0;i<9;i++)c.fillRect(2040+i*48,670,18,175);
 for(let i=0;i<30;i++){const x=360+(i*191)%1800,y=390+(i*137)%980;if(lagoons.some(l=>x>l.x-70&&x<l.x+l.w+70&&y>l.y-70&&y<l.y+l.h+70))continue;palm(c,x,y,.78+(i%4)*.08)}rocks.forEach(r=>{c.fillStyle='#65777b';c.beginPath();c.ellipse(r.x,r.y,r.r,r.r*.68,0,0,Math.PI*2);c.fill()});
 c.fillStyle='#17343b';c.font='800 14px system-ui';lagoons.forEach(z=>c.fillText(z.name.toUpperCase(),z.x+18,z.y-14));c.fillText('CAMP DE BASE',camp.x+18,camp.y+camp.h+28);c.fillText('PLAGE DES PALMES',380,255);
 if(W.fin){c.save();c.translate(W.fin.x,W.fin.y);c.scale(1+Math.sin(W.t*6)*.12,1);c.fillStyle='#243c42';c.beginPath();c.moveTo(-14,12);c.quadraticCurveTo(0,-40,18,12);c.closePath();c.fill();c.strokeStyle='#fff7';c.beginPath();c.ellipse(0,14,36,10,0,0,Math.PI*2);c.stroke();c.restore()}
 drawDog(c,W.dog.x,W.dog.y,W.dog.dir,W.moving);drawHuman(c,S.x,S.y,S.char||'Justine',W.dir,W.moving);c.restore();$('#zoneLabel').textContent=zoneName().toUpperCase()}
function zoneName(){if(S.x>camp.x-40&&S.x<camp.x+camp.w+40&&S.y>camp.y-40&&S.y<camp.y+camp.h+40)return'Camp de base';let z=lagoons.find(z=>S.x>z.x-90&&S.x<z.x+z.w+90&&S.y>z.y-90&&S.y<z.y+z.h+90);if(z)return z.name;if(S.y<420)return'Plage des Palmes';if(S.x>1850)return'Côte Est';return'Jungle intérieure'}
function blocked(x,y){if(x<160||y<160||x>2440||y>1600)return true;if(lagoons.some(l=>x>l.x+35&&x<l.x+l.w-35&&y>l.y+35&&y<l.y+l.h-35))return true;if(rocks.some(r=>Math.hypot(x-r.x,y-r.y)<r.r+25))return true;return false}
function zoneAt(x,y){return lagoons.find(z=>x>z.x-120&&x<z.x+z.w+120&&y>z.y-120&&y<z.y+z.h+120)||null}
function chooseShark(z){let id=z.pool[Math.floor(Math.random()*z.pool.length)];if(Object.keys(S.caught).length>=5&&Math.random()<.07)id='meg';return sharks.find(s=>s.id===id)}
function spawnFin(){const z=lagoons[Math.floor(Math.random()*lagoons.length)],sp=chooseShark(z);W.fin={x:z.x+80+Math.random()*(z.w-160),y:z.y+80+Math.random()*(z.h-160),sp,z,life:12000};W.nextFin=performance.now()+8500+Math.random()*6500}
function update(dt){if($('#game').classList.contains('hidden')||W.battle)return;W.t+=dt;let dx=0,dy=0;if(W.keys.ArrowLeft||W.keys.a||W.touch.left)dx--;if(W.keys.ArrowRight||W.keys.d||W.touch.right)dx++;if(W.keys.ArrowUp||W.keys.w||W.touch.up)dy--;if(W.keys.ArrowDown||W.keys.s||W.touch.down)dy++;if(dx&&dy){dx*=.707;dy*=.707}W.moving=!!(dx||dy);if(Math.abs(dx)>Math.abs(dy)&&dx)W.dir=dx>0?'right':'left';else if(dy)W.dir=dy>0?'down':'up';const nx=S.x+dx*250*dt,ny=S.y+dy*250*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;let ddx=S.x-W.dog.x,ddy=S.y-W.dog.y;if(Math.hypot(ddx,ddy)>76){W.dog.x+=ddx*dt*3.4;W.dog.y+=ddy*dt*3.4;if(Math.abs(ddx)>Math.abs(ddy))W.dog.dir=ddx>0?'right':'left';else W.dog.dir=ddy>0?'down':'up'}
 if(performance.now()>W.nextFin&&!W.fin)spawnFin();if(W.fin){W.fin.life-=dt*1000;if(W.fin.life<0){W.fin=null;W.nextFin=performance.now()+4000}else if(Math.hypot(S.x-W.fin.x,S.y-W.fin.y)<105){const f=W.fin;W.fin=null;startBattle(f.sp,f.z)}}const z=zoneAt(S.x,S.y);if(z&&W.moving&&Math.random()<dt*.08)startBattle(chooseShark(z),z);
 if(S.x>camp.x-35&&S.x<camp.x+camp.w+35&&S.y>camp.y-35&&S.y<camp.y+camp.h+35&&(S.hp<100||S.balls<8)){S.hp=100;S.balls=Math.max(8,S.balls);refresh();save();toast('Camp : énergie restaurée et Pokéballs rechargées.')}drawMap()}
function loop(t){const dt=Math.min(.035,(t-W.last)/1000);W.last=t;update(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function refresh(){const c=Object.keys(S.caught).length;$('#hudPortrait').src=portrait(S.char||'Justine');$('#hudDog').src=A.d;$('#hudName').textContent=S.char||'Justine';$('#hp').textContent=S.hp;$('#hpBar').style.width=S.hp+'%';$('#balls').textContent=S.balls;$('#count').textContent=c;$('#quest').textContent=c<3?`Découvrir 3 espèces de requins (${c}/3).`:c<5?`Trouver 5 espèces pour attirer une présence légendaire (${c}/5).`:c<7?`Le Mégalodon peut désormais apparaître. Complète le SharkDex (${c}/7).`:'SharkDex complet : 7/7 espèces.'}
let tt;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),1800)}
function startGame(reset){if(!S.char)return;if(reset){S={char:S.char,hp:100,balls:8,x:560,y:1180,caught:{},seen:{}};W.dog={x:S.x-58,y:S.y+38,dir:'down'}}$('#start').classList.add('hidden');$('#game').classList.remove('hidden');refresh();drawMap();save()}
$$('.char-card').forEach(b=>b.onclick=()=>{S.char=b.dataset.char;$('.start-bg').style.backgroundImage=`linear-gradient(90deg,#041118f1 0 42%,#0618209b 61%,#0004),url('${portrait(S.char)}')`;$$('.char-card').forEach(x=>x.classList.toggle('selected',x===b));$('#playBtn').disabled=false;$('#playBtn').textContent='Commencer avec '+S.char});$('#playBtn').onclick=()=>startGame(true);if(S.char){$('#resumeBtn').classList.remove('hidden');$('#resumeBtn').onclick=()=>startGame(false);let b=$(`.char-card[data-char="${S.char}"]`);if(b){b.classList.add('selected');$('#playBtn').disabled=false;$('#playBtn').textContent='Nouvelle partie avec '+S.char}}
let bImg=new Image(),rafB=0;
function bgFor(sp){if(sp.id==='white'||sp.id==='meg')return Math.random()<.5?A.bg:A.wide;if(sp.id==='whale'||sp.id==='reef')return Math.random()<.5?A.bj:A.wide;return S.char==='Guillaume'?A.bg:A.bj}
function startBattle(sp,z){if(W.battle)return;W.battle={sp,z,calm:100,shield:false,dogUsed:false,start:performance.now(),attackUntil:0,splash:[]};S.seen[sp.id]=true;save();$('#battle').classList.remove('hidden');$('#battle').classList.toggle('megEncounter',sp.id==='meg');if(sp.id==='meg'){const mt=$('#megTitle');mt.classList.remove('go');void mt.offsetWidth;mt.classList.add('go')}$('#enemyName').textContent=sp.name;$('#enemyRarity').textContent=sp.rare.toUpperCase();$('#enemyTemper').textContent=sp.mood;$('#enemyPct').textContent='100%';$('#enemyBar').style.width='100%';$('#battlePortrait').src=portrait(S.char);$('#battleName').textContent=S.char+' + Syrachi';$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;$('#battleText').textContent=sp.id==='meg'?'L’eau se soulève… le Mégalodon apparaît !':`Un ${sp.name} surgit près de ${z.name.toLowerCase()} !`;setActions(true);bImg.src=bgFor(sp);cancelAnimationFrame(rafB);drawBattle()}
function drawBattle(){if(!W.battle)return;const c=bctx,w=W.vw,h=W.vh,bb=W.battle,sp=bb.sp,age=(performance.now()-bb.start)/1000;c.clearRect(0,0,w,h);if(bImg.complete&&bImg.naturalWidth){let sc=Math.max(w/bImg.naturalWidth,h/bImg.naturalHeight),dw=bImg.naturalWidth*sc,dh=bImg.naturalHeight*sc;c.globalAlpha=.7;c.drawImage(bImg,(w-dw)/2,(h-dh)/2,dw,dh);c.globalAlpha=1}else{let g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#75c8d2');g.addColorStop(1,'#0e4651');c.fillStyle=g;c.fillRect(0,0,w,h)}c.fillStyle='#03101624';c.fillRect(0,0,w,h);c.strokeStyle='#fff6';c.lineWidth=3;for(let i=0;i<10;i++){c.beginPath();c.ellipse((i*153+age*42)%w,h*.45+i*23+Math.sin(age*2+i)*6,75,13,0,0,Math.PI*2);c.stroke()}let x=w*.7+Math.sin(age*sp.spd)*w*.05,y=h*.43+Math.sin(age*1.8)*10,s=Math.min(w/1100,h/680)*(sp.id==='meg'?1.55:sp.id==='whale'?1.3:1);if(performance.now()<bb.attackUntil){let q=1-(bb.attackUntil-performance.now())/520;s*=1+Math.sin(q*Math.PI)*.5;x-=Math.sin(q*Math.PI)*w*.13}drawShark(c,x,y,sp,s,age);for(const p of bb.splash){p.r+=3;p.a-=.04;c.strokeStyle=`rgba(255,255,255,${Math.max(0,p.a)})`;c.beginPath();c.arc(p.x,p.y,p.r,0,Math.PI*2);c.stroke()}bb.splash=bb.splash.filter(p=>p.a>0);rafB=requestAnimationFrame(drawBattle)}
function drawShark(c,x,y,sp,s,t){c.save();c.translate(x,y);c.scale(s,s);c.rotate(Math.sin(t*1.2)*.025);c.fillStyle=sp.c;c.strokeStyle='#28383c';c.lineWidth=3;c.beginPath();c.ellipse(0,0,180,60,0,0,Math.PI*2);c.fill();c.stroke();c.save();c.translate(-160,0);c.rotate(Math.sin(t*4*sp.spd)*.18);c.beginPath();c.moveTo(0,0);c.lineTo(-85,-64);c.lineTo(-64,0);c.lineTo(-85,64);c.closePath();c.fill();c.stroke();c.restore();c.beginPath();c.moveTo(-12,-50);c.lineTo(34,-126);c.lineTo(63,-42);c.closePath();c.fill();c.beginPath();c.moveTo(10,40);c.lineTo(70,105);c.lineTo(90,34);c.closePath();c.fill();if(sp.id==='hammer'){c.fillRect(118,-54,76,28);c.beginPath();c.ellipse(156,-40,42,18,0,0,Math.PI*2);c.fill()}else{c.beginPath();c.ellipse(147,0,73,50,0,0,Math.PI*2);c.fill()}if(sp.id==='tiger'){c.strokeStyle='#443b31';c.lineWidth=7;for(let i=-80;i<90;i+=34){c.beginPath();c.moveTo(i,-44);c.lineTo(i+18,44);c.stroke()}}if(sp.id==='whale'){c.fillStyle='#d7eef0';for(let i=0;i<24;i++){c.beginPath();c.arc(-120+(i*47)%270,-36+((i*31)%72),3,0,Math.PI*2);c.fill()}}c.fillStyle='#dbe2e3';c.beginPath();c.ellipse(64,24,126,26,0,0,Math.PI*2);c.fill();c.fillStyle='#02090c';c.beginPath();c.arc(150,-16,5,0,Math.PI*2);c.fill();c.restore()}
function setActions(on){['observeBtn','captureBtn','dogBtn','runBtn'].forEach(id=>$('#'+id).disabled=!on);if(W.battle?.dogUsed)$('#dogBtn').disabled=true}
function enemyHit(){let b=W.battle,d=b.sp.pow+Math.floor(Math.random()*5);if(b.shield){d=Math.ceil(d/2);b.shield=false}S.hp=Math.max(0,S.hp-d);$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;b.attackUntil=performance.now()+520;b.splash.push({x:W.vw*.65,y:W.vh*.45,r:15,a:.9},{x:W.vw*.72,y:W.vh*.5,r:10,a:.7});document.getElementById('battle').classList.remove('attack');void document.getElementById('battle').offsetWidth;document.getElementById('battle').classList.add('attack');const ring=$('#impactRing');if(ring){ring.classList.remove('go');void ring.offsetWidth;ring.classList.add('go')}save();if(S.hp<=0){$('#battleText').textContent='Syrachi te ramène au camp.';setActions(false);setTimeout(()=>{S.hp=100;S.x=560;S.y=1180;closeBattle()},900);return true}return false}
$('#observeBtn').onclick=()=>{let b=W.battle;if(!b)return;setActions(false);b.calm=Math.max(5,b.calm-(18+Math.floor(Math.random()*18)));$('#enemyPct').textContent=b.calm+'%';$('#enemyBar').style.width=b.calm+'%';$('#battleText').textContent=b.sp.id==='meg'?'Tu étudies son rythme colossal… chaque seconde compte.':'Tu observes ses mouvements…';setTimeout(()=>{if(b.sp.id==='whale'&&Math.random()<.6){$('#battleText').textContent+=' Il reste paisible.';setActions(true)}else if(!enemyHit()){ $('#battleText').textContent+=' Il riposte !';setActions(true)}},650)};
$('#dogBtn').onclick=()=>{let b=W.battle;if(!b||b.dogUsed)return;b.shield=true;b.dogUsed=true;$('#battleText').textContent='Syrachi détourne son attention.';$('#dogBtn').disabled=true};
$('#captureBtn').onclick=()=>{let b=W.battle;if(!b)return;if(S.balls<=0){$('#battleText').textContent='Plus de Pokéballs.';return}S.balls--;$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;setActions(false);let fx=$('#ballFx');fx.classList.remove('go');void fx.offsetWidth;fx.classList.add('go');let chance=Math.min(.94,b.sp.base+(100-b.calm)/125+(b.dogUsed?.04:0));$('#battleText').textContent='Pokéball lancée…';setTimeout(()=>{if(Math.random()<chance){S.caught[b.sp.id]=(S.caught[b.sp.id]||0)+1;S.seen[b.sp.id]=true;save();let f=$('#captureFlash');f.classList.remove('go');void f.offsetWidth;f.classList.add('go');$('#battleText').textContent=`${b.sp.name} capturé !`;setTimeout(()=>{closeBattle();refresh();toast('Capture ajoutée au SharkDex !')},950)}else{$('#battleText').textContent='Il se libère !';if(!enemyHit())setActions(true)}},850)};
$('#runBtn').onclick=()=>{if(!W.battle)return;setActions(false);if(Math.random()<(W.battle&&W.battle.sp.id==='meg'?0.58:0.82)){$('#battleText').textContent='Vous vous éloignez avec Syrachi.';setTimeout(closeBattle,500)}else{$('#battleText').textContent='Le requin vous coupe la route !';setTimeout(()=>{if(!enemyHit())setActions(true)},450)}};
function closeBattle(){cancelAnimationFrame(rafB);W.battle=null;$('#battle').classList.add('hidden');$('#battle').classList.remove('megEncounter');refresh();save();W.nextFin=performance.now()+5000}
function renderDex(){let g=$('#dexGrid');g.innerHTML='';sharks.forEach(sp=>{let seen=S.seen[sp.id]||S.caught[sp.id],n=S.caught[sp.id]||0,d=document.createElement('button');d.className='dexCard'+(seen?'':' lock');d.innerHTML=`<div class="dexIcon">${seen?'🦈':'❔'}</div><div><b>${seen?sp.name:'Espèce inconnue'}</b><small>${seen?`${sp.rare} • x${n}`:'Non découverte'}</small></div>`;d.onclick=()=>{$('#dexName').textContent=seen?sp.name:'Espèce inconnue';$('#dexInfo').textContent=seen?`${sp.rare} • ${sp.mood} • capturé x${n}`:'Explore les lagons pour découvrir cette espèce.'};g.appendChild(d)})}
$('#dexBtn').onclick=()=>{renderDex();$('#dex').classList.remove('hidden')};$('#closeDex').onclick=()=>$('#dex').classList.add('hidden');addEventListener('keydown',e=>W.keys[e.key]=1);addEventListener('keyup',e=>W.keys[e.key]=0);$$('.dpad button').forEach(b=>{let d=b.dataset.dir;b.onpointerdown=e=>{e.preventDefault();W.touch[d]=1};b.onpointerup=b.onpointercancel=b.onpointerout=e=>{e.preventDefault();W.touch[d]=0}});refresh();drawMap();
})();
