(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SAVE='sharkquest-v31';
const A={Justine:null,Guillaume:null,dog:null,explore:null,battle:{Justine:null,Guillaume:null}};
const sharks=[{id:'recif',name:'Requin de récif',rarity:'Commun',base:.68,power:6},{id:'marteau',name:'Requin marteau',rarity:'Commun',base:.58,power:8},{id:'tigre',name:'Requin tigre',rarity:'Peu commun',base:.48,power:10},{id:'mako',name:'Requin mako',rarity:'Rare',base:.39,power:12},{id:'blanc',name:'Grand requin blanc',rarity:'Rare',base:.31,power:15},{id:'baleine',name:'Requin-baleine',rarity:'Très rare',base:.25,power:9},{id:'meg',name:'Mégalodon',rarity:'Légendaire',base:.15,power:19}];
const MAP=[['rock','rock','water','water','rock'],['path','reed','path','reed','water'],['hut','path','path','reed','water'],['rock','path','reed','path','rock']];
const Z={rock:['Falaises','Passage rocheux.'],water:['Lagune','Courants rapides.'],reed:['Roseaux du lagon','Zone de rencontre.'],path:['Sentier côtier','Terrain sûr.'],hut:['Cabane','Repos et recharge.']};
let selected=window.__pendingCharacter||null,battle=null,busy=false,state={char:'Justine',x:1,y:2,energy:100,balls:8,caught:{},steps:0};
window.pickCharacter=(name,el)=>{selected=name;window.__pendingCharacter=name;$$('.choice').forEach(x=>x.classList.remove('sel'));if(el)el.classList.add('sel');const b=$('#newGame');b.disabled=false;b.textContent='Commencer avec '+name;};
async function one(file){try{const r=await fetch('assets/'+file+'.b64',{cache:'no-store'});if(!r.ok)throw 0;const t=(await r.text()).trim();const b=atob(t),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return URL.createObjectURL(new Blob([u],{type:'image/webp'}))}catch(e){return null}}
async function loadAssets(){const n=['justine','guillaume','syrachi','explore','battle_justine','battle_guillaume'];const v=await Promise.all(n.map(one));[A.Justine,A.Guillaume,A.dog,A.explore,A.battle.Justine,A.battle.Guillaume]=v;if(A.Justine)$('#choiceJustine').src=A.Justine;if(A.Guillaume)$('#choiceGuillaume').src=A.Guillaume;if(A.dog)$('#hudDog').src=A.dog;if(A.explore){const st=document.createElement('style');st.textContent=`.start::before,.worldbg{background-image:url('${A.explore}')!important}`;document.head.appendChild(st)}if(!$('#game').classList.contains('hidden'))draw()}
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}function load(){try{const x=JSON.parse(localStorage.getItem(SAVE));if(x&&x.char){state={...state,...x};return true}}catch(e){}return false}
function type(){return MAP[state.y][state.x]}function hud(){const sp=Object.keys(state.caught).length,total=Object.values(state.caught).reduce((a,b)=>a+b,0);if(A[state.char])$('#hudAvatar').src=A[state.char];$('#hudName').textContent=state.char;$('#energy').textContent=state.energy;$('#balls').textContent=state.balls;$('#count').textContent=total;$('#objective').textContent=sp>=5?`Objectif accompli : ${sp}/7 espèces découvertes.`:`Capture 5 espèces différentes — ${sp}/5.`;if(A.battle[state.char])$('#battlebg').style.backgroundImage=`url('${A.battle[state.char]}')`}
function mini(){const g=$('#miniGrid');g.innerHTML='';MAP.forEach((r,y)=>r.forEach((t,x)=>{const d=document.createElement('div');d.className='cell '+t+(x===state.x&&y===state.y?' player':'');g.appendChild(d)}))}
function zone(){const z=Z[type()];$('#zoneTitle').innerHTML=`<b>${z[0]}</b><small>${z[1]}</small>`;$('#worldbg').style.transform=`scale(1.04) translate(${(2-state.x)*1.5}%,${(1.5-state.y)*1.2}%)`}
function draw(){hud();mini();zone()}let tt;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),1700)}
function move(dx,dy){if(busy||battle)return;const nx=state.x+dx,ny=state.y+dy;if(nx<0||ny<0||ny>=MAP.length||nx>=MAP[0].length||MAP[ny][nx]==='rock'){toast('Passage impossible.');return}state.x=nx;state.y=ny;state.steps++;$('#world').classList.add('move');setTimeout(()=>$('#world').classList.remove('move'),280);if(type()==='hut'){state.energy=100;state.balls=Math.max(8,state.balls);toast('Cabane : énergie restaurée et Pokéballs rechargées.')}draw();save();if(type()==='reed'&&Math.random()<.32){busy=true;$('#flash').classList.add('go');setTimeout(()=>$('#flash').classList.remove('go'),700);setTimeout(startBattle,430)}}
function pick(){const r=Math.random();return r<.28?sharks[0]:r<.51?sharks[1]:r<.69?sharks[2]:r<.82?sharks[3]:r<.92?sharks[4]:r<.985?sharks[5]:sharks[6]}
function startBattle(){busy=false;const s=pick(),lvl=2+Math.floor(state.steps/8)+Math.floor(Math.random()*3);battle={s,lvl,hp:100,shield:false,dogUsed:false};$('#enemyName').textContent=s.name;$('#enemyMeta').textContent=`Niv. ${lvl} • ${s.rarity}`;$('#enemyHp').style.width='100%';$('#battleStatus').textContent='Le requin vous observe…';$('#battleText').textContent=`Un ${s.name} surgit devant ${state.char} et Syrachi. Observe-le pour augmenter tes chances de capture.`;if(A.battle[state.char])$('#battlebg').style.backgroundImage=`url('${A.battle[state.char]}')`;$('#battleModal').classList.remove('hidden');battleControls(true)}
function battleControls(on){$$('#battleModal .actions button').forEach(b=>b.disabled=!on);if(battle)$('#dogBtn').disabled=battle.dogUsed||!on}
function riposte(){let d=battle.s.power+Math.floor(Math.random()*6);if(battle.shield){d=Math.ceil(d/2);battle.shield=false}state.energy=Math.max(0,state.energy-d);hud();save();$('#battleStatus').textContent=`Riposte : -${d} énergie`;if(state.energy<=0){battleControls(false);$('#battleText').textContent='Tu es épuisé·e. Syrachi te ramène à la cabane.';setTimeout(()=>{state.x=0;state.y=2;state.energy=100;battle=null;$('#battleModal').classList.add('hidden');draw();save();toast('Syrachi t’a ramené·e en sécurité.')},1000);return true}return false}
function observe(){battleControls(false);const d=16+Math.floor(Math.random()*18);battle.hp=Math.max(8,battle.hp-d);$('#enemyHp').style.width=battle.hp+'%';$('#battleText').textContent=`Tu observes ses mouvements : -${d} de résistance.`;setTimeout(()=>{if(!riposte()){ $('#battleText').textContent+=' Il contre-attaque !';battleControls(true)}},650)}
function dogHelp(){battle.shield=true;battle.dogUsed=true;$('#battleText').textContent='Syrachi détourne son attention. La prochaine riposte est divisée par deux.';$('#dogBtn').disabled=true}
function capture(){if(state.balls<=0){$('#battleText').textContent='Plus de Pokéballs : retourne à la cabane.';return}state.balls--;hud();save();battleControls(false);const chance=Math.min(.94,battle.s.base+(100-battle.hp)/125);$('#battleText').textContent=`${state.char} lance une Pokéball…`;setTimeout(()=>{if(Math.random()<chance){state.caught[battle.s.id]=(state.caught[battle.s.id]||0)+1;hud();save();$('#battleText').textContent=`Capturé ! ${battle.s.name} rejoint le SharkDex.`;setTimeout(()=>{battle=null;$('#battleModal').classList.add('hidden');toast('Nouveau requin capturé !')},850)}else{$('#battleText').textContent='Il se libère !';if(!riposte())setTimeout(()=>battleControls(true),350)}},850)}
function runAway(){battleControls(false);if(Math.random()<.82){$('#battleText').textContent='Vous reculez prudemment avec Syrachi.';setTimeout(()=>{battle=null;$('#battleModal').classList.add('hidden')},450)}else{$('#battleText').textContent='Impossible de fuir !';if(!riposte())setTimeout(()=>battleControls(true),350)}}
function showDex(){const g=$('#dexGrid');g.innerHTML='';sharks.forEach(s=>{const n=state.caught[s.id]||0,d=document.createElement('div');d.className='dexitem'+(n?'':' lock');d.innerHTML=`<b>${n?s.name:'Espèce inconnue'}</b><div class='small'>${n?`${s.rarity} • capturé x${n}`:'Explore les roseaux du lagon.'}</div>`;g.appendChild(d)});$('#dexModal').classList.remove('hidden')}
function showBag(){$('#bagGrid').innerHTML=`<div class='bagitem'><b>🔴 Pokéballs : ${state.balls}</b></div><div class='bagitem'><b>❤️ Énergie : ${state.energy}/100</b></div><div class='bagitem'><b>🐕 Syrachi : protection 1× par rencontre</b></div>`;$('#bagModal').classList.remove('hidden')}
function enter(){state.char=selected||state.char;$('#start').classList.add('hidden');$('#game').classList.remove('hidden');draw();save()}
function init(){const ng=$('#newGame');ng.addEventListener('click',()=>{if(!selected)return;state={char:selected,x:1,y:2,energy:100,balls:8,caught:{},steps:0};enter()});if(load()){$('#resume').classList.remove('hidden');$('#resume').onclick=()=>{selected=state.char;enter()}}$$('[data-dir]').forEach(b=>b.onclick=()=>{const d=b.dataset.dir;move(d==='right'?1:d==='left'?-1:0,d==='down'?1:d==='up'?-1:0)});$('#observe').onclick=observe;$('#catch').onclick=capture;$('#dogBtn').onclick=dogHelp;$('#run').onclick=runAway;$('#dexBtn').onclick=showDex;$('#bagBtn').onclick=showBag;$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close+'Modal').classList.add('hidden'));loadAssets()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();