(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const worldCanvas=$('#world'), ctx=worldCanvas.getContext('2d'), battleCanvas=$('#battleCanvas'), bctx=battleCanvas.getContext('2d');
const KEY='sharkquest-v56';
const species=[
 {id:'reef',name:'Requin de récif',rarity:'Commun',temper:'Curieux',base:.67,power:6,speed:.78,color:'#7f9aa2',zone:['lagoon','beach'],desc:'Petit requin côtier curieux, souvent visible dans les eaux peu profondes.'},
 {id:'hammer',name:'Requin marteau',rarity:'Peu commun',temper:'Méfiant',base:.56,power:8,speed:1.02,color:'#74878c',zone:['lagoon','pontoon'],desc:'Sa tête en marteau lui donne une silhouette impossible à confondre.'},
 {id:'tiger',name:'Requin tigre',rarity:'Peu commun',temper:'Agressif',base:.46,power:12,speed:.92,color:'#887963',zone:['beach','lagoon'],desc:'Robuste et opportuniste. Ses rayures sombres deviennent plus discrètes avec l’âge.'},
 {id:'mako',name:'Requin mako',rarity:'Rare',temper:'Très rapide',base:.37,power:11,speed:1.35,color:'#527d90',zone:['pontoon','deep'],desc:'Un des requins les plus rapides. Difficile à observer longtemps.'},
 {id:'white',name:'Grand requin blanc',rarity:'Rare',temper:'Prédateur',base:.30,power:15,speed:1.0,color:'#80949a',zone:['deep','pontoon'],desc:'Puissant prédateur côtier, rare autour des lagons les plus profonds.'},
 {id:'whale',name:'Requin-baleine',rarity:'Très rare',temper:'Paisible',base:.52,power:4,speed:.58,color:'#436e7d',zone:['deep'],desc:'Un géant paisible couvert de points clairs. Une rencontre exceptionnelle.'},
 {id:'meg',name:'Mégalodon',rarity:'Légendaire',temper:'Boss',base:.11,power:21,speed:.88,color:'#394a4e',zone:['boss'],desc:'Une présence gigantesque. Il n’apparaît qu’après avoir prouvé ta maîtrise de l’île.'}
];
let S={char:null,hp:100,balls:8,x:575,y:1190,caught:{},seen:{},quest:0}; try{Object.assign(S,JSON.parse(localStorage.getItem(KEY))||{})}catch{};
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const ASSET={
  justinePortrait:'../v52/assets/justine.webp',
  guillaumePortrait:'../v52/assets/guillaume.webp',
  syrachiPortrait:'../v52/assets/syrachi.webp',
  battleJustine:'../v52/assets/battle_justine.webp',
  battleGuillaume:'../v52/assets/battle_guillaume.webp',
  encounterTropical:'../v52/battle.webp',
  encounterLagoon:'../v52/assets/battle_justine.webp',
  encounterWhite1:'../v52/assets/battle_guillaume.webp',
  encounterWhite2:'../v52/battle.webp'
};
const IMG={};
const portrait=n=>n==='Guillaume'?ASSET.guillaumePortrait:ASSET.justinePortrait;
const spriteImg=n=>n==='Guillaume'?IMG.guillaumeSprite:IMG.justineSprite;
function battleChoices(char,sp){
  const charMain=char==='Guillaume'?ASSET.battleGuillaume:ASSET.battleJustine;
  if(sp.id==='white'||sp.id==='meg') return [ASSET.encounterWhite1,ASSET.encounterWhite2,charMain];
  if(sp.id==='whale') return [ASSET.encounterLagoon,ASSET.encounterTropical,charMain];
  if(sp.id==='hammer'||sp.id==='mako') return [charMain,ASSET.encounterLagoon,ASSET.encounterTropical];
  return [charMain,ASSET.encounterTropical,ASSET.encounterLagoon,ASSET.encounterWhite2];
}
function randPick(arr){return arr[Math.floor(Math.random()*arr.length)]}
const W={w:2600,h:1800,camX:0,camY:0,keys:{},touch:{},last:performance.now(),dog:{x:S.x-50,y:S.y+35},trail:[],fin:null,nextFin:0,battle:null,zone:'Camp de base',t:0,dir:'down',dogDir:'down',moving:false,dogMoving:false};
const lagoons=[
 {id:'turq',type:'lagoon',name:'Lagon turquoise',x:430,y:420,w:540,h:330,weights:['reef','reef','hammer','tiger']},
 {id:'north',type:'deep',name:'Lagon nord',x:1560,y:360,w:590,h:360,weights:['hammer','mako','white','whale']},
 {id:'reeds',type:'lagoon',name:'Lagon des roseaux',x:820,y:1030,w:780,h:300,weights:['reef','tiger','hammer','white']},
 {id:'pontoon',type:'pontoon',name:'Ponton abandonné',x:2050,y:700,w:360,h:240,weights:['hammer','mako','white']},
 {id:'beach',type:'beach',name:'Plage des Palmes',x:260,y:250,w:2080,h:1280,weights:['reef','tiger']}
];
const camp={x:300,y:1280,w:330,h:230};
const rocks=[{x:690,y:820,r:58},{x:1250,y:760,r:52},{x:1830,y:1000,r:70},{x:680,y:1380,r:50},{x:1450,y:510,r:42}];
function preload(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error(src));i.src=src})}
function setStartBackground(char){const src=char==='Guillaume'?ASSET.guillaumePortrait:ASSET.justinePortrait;$('.start-bg').style.backgroundImage=`linear-gradient(90deg,#041118f2 0 42%,#0618209e 61%,#0005), url('${src}')`;}
async function spriteFromB64(b64){const raw=atob(b64),u=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)u[i]=raw.charCodeAt(i);const url=URL.createObjectURL(new Blob([u],{type:'image/webp'}));return preload(url)}
async function loadVisuals(){
 try{
  const [j,g,d,bj,bg,et]=await Promise.all([preload(ASSET.justinePortrait),preload(ASSET.guillaumePortrait),preload(ASSET.syrachiPortrait),preload(ASSET.battleJustine),preload(ASSET.battleGuillaume),preload(ASSET.encounterTropical)]);
  IMG.justinePortrait=j;IMG.guillaumePortrait=g;IMG.syrachiPortrait=d;IMG.battleJustine=bj;IMG.battleGuillaume=bg;IMG.encounterTropical=et;
  const parts=await Promise.all([0,1,2,3,4].map(i=>fetch(`sprite_parts/part${i}.txt`,{cache:'no-store'}).then(r=>r.text())));
  const [jb,gb,db]=parts.join('').split('~NEXT~');
  [IMG.justineSprite,IMG.guillaumeSprite,IMG.syrachiSprite]=await Promise.all([spriteFromB64(jb),spriteFromB64(gb),spriteFromB64(db)]);
  $('#justineCardImg').src=ASSET.justinePortrait;$('#guillaumeCardImg').src=ASSET.guillaumePortrait;$('#syrachiCardImg').src=ASSET.syrachiPortrait;$('#hudDog').src=ASSET.syrachiPortrait;setStartBackground(S.char||'Justine');document.body.classList.add('visualsReady');
 }catch(e){console.warn('asset load error',e)}finally{$('#loading').style.display='none'}
}
loadVisuals();
function fit(){const d=Math.min(devicePixelRatio||1,2);for(const c of [worldCanvas,battleCanvas]){c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';c.width=Math.round(innerWidth*d);c.height=Math.round(innerHeight*d);c.getContext('2d').setTransform(d,0,0,d,0,0)}ctx.imageSmoothingEnabled=true;bctx.imageSmoothingEnabled=true;W.vw=innerWidth;W.vh=innerHeight}addEventListener('resize',fit);fit();
const rr=(c,x,y,w,h,r,color)=>{c.fillStyle=color;c.beginPath();c.roundRect(x,y,w,h,r);c.fill()};
function water(c,x,y,w,h,alpha=1){rr(c,x,y,w,h,90,'#48b5c2');c.save();c.globalAlpha=.32*alpha;c.strokeStyle='#d7fbff';c.lineWidth=2;for(let yy=y+25;yy<y+h;yy+=46)for(let xx=x+20+((yy/46)%2)*22;xx<x+w;xx+=80){c.beginPath();c.ellipse(xx+Math.sin(W.t*1.8+yy)*5,yy,26,6,0,0,Math.PI*2);c.stroke()}c.restore()}
function palm(c,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);c.strokeStyle='#5a3d27';c.lineWidth=9;c.beginPath();c.moveTo(0,36);c.quadraticCurveTo(5,-15,-4,-58);c.stroke();c.fillStyle='#397a45';for(let a=0;a<6;a++){c.save();c.rotate(a*Math.PI/3+Math.sin(W.t+x)*.03);c.beginPath();c.ellipse(20,-58,35,8,-.4,0,Math.PI*2);c.fill();c.restore()}c.restore()}
function reeds(c,l){c.strokeStyle='#3f753c';c.lineWidth=3;for(let x=l.x+14;x<l.x+l.w-14;x+=24){const sway=Math.sin(W.t*2+x*.02)*5;c.beginPath();c.moveTo(x,l.y+l.h-8);c.quadraticCurveTo(x+sway,l.y+l.h*.58,x+sway*.5,l.y+45);c.stroke();c.fillStyle='#d6bd69';c.fillRect(x+sway*.5-2,l.y+32,4,14)}}
function currentZone(){if(S.x>camp.x-40&&S.x<camp.x+camp.w+40&&S.y>camp.y-40&&S.y<camp.y+camp.h+40)return 'Camp de base';let z=lagoons.find(z=>S.x>z.x-80&&S.x<z.x+z.w+80&&S.y>z.y-80&&S.y<z.y+z.h+80);if(z)return z.name;if(S.y<420)return 'Plage des Palmes';if(S.x>1850)return 'Côte Est';return 'Jungle intérieure'}
function frameFor(dir,moving){const step=Math.floor(W.t*9)%2;if(dir==='down')return{row:0,col:moving?(step?1:0):0};if(dir==='up')return{row:0,col:moving?(step?3:2):2};if(dir==='left')return{row:1,col:moving?(step?1:0):0};return{row:1,col:moving?(step?3:2):2};}
function drawEntity(c,img,x,y,dir,moving,kind='human'){if(!img||!img.complete||!img.naturalWidth)return;const cols=4,rows=2,sw=img.naturalWidth/cols,sh=img.naturalHeight/rows;const fr=frameFor(dir,moving);const padX=sw*.06,padY=sh*.05;const sx=fr.col*sw+padX,sy=fr.row*sh+padY,sW=sw-padX*2,sH=sh-padY*2;const scale=kind==='dog'?.22:.27;const dw=sW*scale,dh=sH*scale;c.save();c.translate(x,y+(kind==='dog'?0:2*Math.sin(W.t*9)));c.fillStyle='rgba(0,0,0,.28)';c.beginPath();c.ellipse(0,kind==='dog'?28:38,kind==='dog'?30:32,kind==='dog'?9:11,0,0,Math.PI*2);c.fill();c.strokeStyle=kind==='dog'?'rgba(107,213,223,.8)':(S.char==='Justine'?'rgba(242,138,52,.9)':'rgba(107,213,223,.9)');c.lineWidth=4;c.beginPath();c.arc(0,kind==='dog'?6:8,kind==='dog'?24:28,0,Math.PI*2);c.stroke();c.shadowColor='rgba(0,0,0,.45)';c.shadowBlur=12;c.shadowOffsetY=6;if(dir==='left'&&kind==='dog')c.scale(-1,1);c.drawImage(img,sx,sy,sW,sH,-dw/2,-dh*.8,dw,dh);c.shadowColor='transparent';if(kind==='human'){c.fillStyle='rgba(6,23,29,.85)';c.beginPath();c.roundRect(-36,-dh*.95,72,20,10);c.fill();c.fillStyle='#fff';c.font='700 11px system-ui';c.textAlign='center';c.fillText(S.char||'Justine',0,-dh*.95+14)}c.restore()}
function drawMap(){const c=ctx,VW=W.vw,VH=W.vh;c.clearRect(0,0,VW,VH);W.camX=Math.max(0,Math.min(W.w-VW,S.x-VW/2));W.camY=Math.max(0,Math.min(W.h-VH,S.y-VH/2));c.save();c.translate(-W.camX,-W.camY);c.fillStyle='#2e98a8';c.fillRect(0,0,W.w,W.h);for(let yy=15;yy<W.h;yy+=55)for(let xx=(yy%110?0:35);xx<W.w;xx+=90){c.strokeStyle='#ffffff20';c.lineWidth=2;c.beginPath();c.ellipse(xx+Math.sin(W.t+yy)*5,yy,30,7,0,0,Math.PI*2);c.stroke()}rr(c,120,105,2360,1580,210,'#e4c77f');rr(c,270,280,2050,1210,165,'#5c9952');rr(c,340,345,1910,1080,130,'#78b260');rr(c,500,1260,1530,120,48,'#d4b36f');rr(c,1170,690,130,640,48,'#d4b36f');rr(c,770,310,1210,92,36,'#d4b36f');for(const z of lagoons.filter(x=>x.id!=='beach'&&x.id!=='pontoon')){water(c,z.x,z.y,z.w,z.h);reeds(c,z)}rr(c,camp.x,camp.y,camp.w,camp.h,28,'#725138');c.fillStyle='#b95449';c.beginPath();c.moveTo(camp.x-25,camp.y+30);c.lineTo(camp.x+camp.w/2,camp.y-105);c.lineTo(camp.x+camp.w+25,camp.y+30);c.fill();rr(c,camp.x+135,camp.y+105,60,125,8,'#3c2d25');c.fillStyle='#735039';c.fillRect(2030,715,430,90);for(let i=0;i<9;i++)c.fillRect(2040+i*48,670,18,175);for(let i=0;i<28;i++){const x=360+(i*191)%1800,y=390+(i*137)%980;if(lagoons.some(l=>l.id!=='beach'&&l.id!=='pontoon'&&x>l.x-80&&x<l.x+l.w+80&&y>l.y-80&&y<l.y+l.h+80))continue;palm(c,x,y,.78+(i%4)*.08)}rocks.forEach(r=>{c.fillStyle='#637579';c.beginPath();c.ellipse(r.x,r.y,r.r,r.r*.68,0,0,Math.PI*2);c.fill();c.fillStyle='#91a2a4';c.beginPath();c.ellipse(r.x-12,r.y-14,r.r*.42,r.r*.2,-.4,0,Math.PI*2);c.fill()});for(const [x,y] of [[650,1290],[720,1290],[2140,825]]){rr(c,x,y,52,42,4,'#8a5d35');c.strokeStyle='#c89555';c.strokeRect(x+5,y+5,42,32)}c.fillStyle='#ef6c55';c.beginPath();c.arc(2200,650,16,0,Math.PI*2);c.fill();c.strokeStyle='#fff';c.lineWidth=6;c.beginPath();c.arc(2200,650,9,0,Math.PI*2);c.stroke();c.font='800 15px system-ui';c.fillStyle='#17343b';for(const z of lagoons.filter(x=>x.id!=='beach'))c.fillText(z.name.toUpperCase(),z.x+20,z.y-16);c.fillText('CAMP DE BASE',camp.x+18,camp.y+camp.h+30);c.fillText('PLAGE DES PALMES',380,255);if(W.fin){const f=W.fin,pulse=1+Math.sin(W.t*5)*.12;c.save();c.translate(f.x,f.y);c.scale(pulse,pulse);c.fillStyle='#263e45';c.beginPath();c.moveTo(-14,12);c.quadraticCurveTo(0,-38,17,11);c.closePath();c.fill();c.strokeStyle='#ffffff66';c.lineWidth=2;c.beginPath();c.ellipse(0,14,35,10,0,0,Math.PI*2);c.stroke();c.restore()}drawEntity(c,IMG.syrachiSprite,W.dog.x,W.dog.y,W.dogDir,W.dogMoving,'dog');drawEntity(c,spriteImg(S.char||'Justine'),S.x,S.y,W.dir,W.moving,'human');c.restore();W.zone=currentZone();$('#zoneLabel').textContent=W.zone.toUpperCase()}
function blocked(x,y){if(x<160||y<160||x>2440||y>1600)return true;if(lagoons.filter(z=>z.id!=='beach'&&z.id!=='pontoon').some(l=>x>l.x+35&&x<l.x+l.w-35&&y>l.y+35&&y<l.y+l.h-35))return true;if(rocks.some(r=>Math.hypot(x-r.x,y-r.y)<r.r+24))return true;return false}
function zoneAt(x,y){return lagoons.find(z=>z.id!=='beach'&&x>z.x-120&&x<z.x+z.w+120&&y>z.y-120&&y<z.y+z.h+120)||null}
function spawnFin(){const candidates=lagoons.filter(z=>z.id!=='beach'),z=candidates[Math.floor(Math.random()*candidates.length)];let id=z.weights[Math.floor(Math.random()*z.weights.length)];if(Object.keys(S.caught).length>=5&&Math.random()<.08)id='meg';const sp=species.find(s=>s.id===id);W.fin={x:z.x+70+Math.random()*(z.w-140),y:z.y+70+Math.random()*(z.h-140),species:sp,zone:z,life:12000};W.nextFin=performance.now()+9000+Math.random()*7000}
function pickSpecies(z){let id=z.weights[Math.floor(Math.random()*z.weights.length)];if(Object.keys(S.caught).length>=5&&Math.random()<.06)id='meg';return species.find(s=>s.id===id)}
function update(dt){if($('#game').classList.contains('hidden')||W.battle)return;W.t+=dt;let dx=0,dy=0;if(W.keys.ArrowLeft||W.keys.a||W.touch.left)dx--;if(W.keys.ArrowRight||W.keys.d||W.touch.right)dx++;if(W.keys.ArrowUp||W.keys.w||W.touch.up)dy--;if(W.keys.ArrowDown||W.keys.s||W.touch.down)dy++;if(dx&&dy){dx*=.707;dy*=.707}const speed=250,nx=S.x+dx*speed*dt,ny=S.y+dy*speed*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;W.moving=!!(dx||dy);if(Math.abs(dx)>Math.abs(dy)&&dx)W.dir=dx>0?'right':'left';else if(dy)W.dir=dy>0?'down':'up';if(dx||dy){W.trail.push([S.x,S.y]);if(W.trail.length>16){const p=W.trail.shift(),oldX=W.dog.x,oldY=W.dog.y;W.dog.x+=(p[0]-W.dog.x)*Math.min(1,dt*7);W.dog.y+=(p[1]-W.dog.y)*Math.min(1,dt*7);const ddx=W.dog.x-oldX,ddy=W.dog.y-oldY;W.dogMoving=Math.hypot(ddx,ddy)>.1;if(Math.abs(ddx)>Math.abs(ddy)&&Math.abs(ddx)>.01)W.dogDir=ddx>0?'right':'left';else if(Math.abs(ddy)>.01)W.dogDir=ddy>0?'down':'up'}}else{const oldX=W.dog.x,oldY=W.dog.y;W.dog.x+=(S.x-48-W.dog.x)*Math.min(1,dt*2.6);W.dog.y+=(S.y+38-W.dog.y)*Math.min(1,dt*2.6);const ddx=W.dog.x-oldX,ddy=W.dog.y-oldY;W.dogMoving=Math.hypot(ddx,ddy)>.05;if(Math.abs(ddx)>Math.abs(ddy)&&Math.abs(ddx)>.01)W.dogDir=ddx>0?'right':'left';else if(Math.abs(ddy)>.01)W.dogDir=ddy>0?'down':'up'}if(performance.now()>W.nextFin&&!W.fin)spawnFin();if(W.fin){W.fin.life-=dt*1000;W.fin.x+=Math.sin(W.t*1.4)*7*dt;W.fin.y+=Math.cos(W.t*1.1)*4*dt;if(W.fin.life<=0){W.fin=null;W.nextFin=performance.now()+5000}else if(Math.hypot(S.x-W.fin.x,S.y-W.fin.y)<110){const f=W.fin;W.fin=null;startBattle(f.species,f.zone)}}const z=zoneAt(S.x,S.y);if(z&&dx+dy!==0&&Math.random()<dt*.10)startBattle(pickSpecies(z),z);if(S.x>camp.x-35&&S.x<camp.x+camp.w+35&&S.y>camp.y-35&&S.y<camp.y+camp.h+35&&(S.hp<100||S.balls<8)){S.hp=100;S.balls=Math.max(S.balls,8);refresh();save();toast('Camp : énergie restaurée et Pokéballs rechargées.')}drawMap()}
function loop(t){const dt=Math.min(.035,(t-W.last)/1000);W.last=t;update(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function refresh(){const caught=Object.keys(S.caught).length;$('#hudPortrait').src=portrait(S.char||'Justine');$('#hudDog').src=ASSET.syrachiPortrait;$('#hudName').textContent=S.char||'Justine';$('#hp').textContent=S.hp;$('#hpBar').style.width=S.hp+'%';$('#balls').textContent=S.balls;$('#count').textContent=caught;$('#quest').textContent=caught<3?`Découvrir 3 espèces de requins (${caught}/3).`:caught<5?`Trouver 5 espèces pour attirer une présence légendaire (${caught}/5).`:caught<7?`Le Mégalodon peut désormais apparaître. Complète le SharkDex (${caught}/7).`:'SharkDex complet : 7/7 espèces.'}
let tt;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),1800)}
function startGame(newGame=false){if(!S.char)return;if(newGame){S={char:S.char,hp:100,balls:8,x:575,y:1190,caught:{},seen:{},quest:0};W.dog={x:S.x-50,y:S.y+35};W.fin=null;W.dir='down';W.dogDir='down'}$('#start').classList.add('hidden');$('#game').classList.remove('hidden');refresh();drawMap();save()}
$$('.char-card').forEach(b=>b.onclick=()=>{S.char=b.dataset.char;setStartBackground(S.char);$$('.char-card').forEach(x=>x.classList.toggle('selected',x===b));$('#playBtn').disabled=false;$('#playBtn').textContent='Commencer avec '+S.char});$('#playBtn').onclick=()=>startGame(true);if(S.char){$('#resumeBtn').classList.remove('hidden');$('#resumeBtn').onclick=()=>startGame(false);const b=$(`.char-card[data-char="${S.char}"]`);if(b){b.classList.add('selected');$('#playBtn').disabled=false;$('#playBtn').textContent='Nouvelle partie avec '+S.char;setStartBackground(S.char)}}
let bImg=new Image(),battleRAF=0;
function startBattle(sp,z){if(W.battle)return;W.battle={sp,z,calm:100,shield:false,dogUsed:false,start:performance.now(),attackUntil:0,splash:[],bg:randPick(battleChoices(S.char,sp))};S.seen[sp.id]=true;save();$('#battle').classList.remove('hidden');$('#enemyName').textContent=sp.name;$('#enemyRarity').textContent=sp.rarity.toUpperCase();$('#enemyTemper').textContent=sp.temper;$('#enemyPct').textContent='100%';$('#enemyBar').style.width='100%';$('#battlePortrait').src=portrait(S.char);$('#battleName').textContent=S.char+' + Syrachi';$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;$('#battleText').textContent=introFor(sp,z);setActions(true);bImg.src=W.battle.bg;cancelAnimationFrame(battleRAF);drawBattle()}
function introFor(sp,z){if(sp.id==='meg')return 'L’eau se soulève brutalement… une silhouette gigantesque approche. Le Mégalodon apparaît !';if(sp.id==='whale')return `Une immense ombre paisible traverse ${z.name.toLowerCase()} : un Requin-baleine !`;if(sp.id==='mako')return 'Une silhouette fend l’eau à toute vitesse : un Requin mako surgit !';return `Un ${sp.name} apparaît près de ${z.name.toLowerCase()} !`}
function drawBattle(){if(!W.battle)return;const c=bctx,w=W.vw,h=W.vh;c.clearRect(0,0,w,h);if(bImg.complete&&bImg.naturalWidth){const scale=Math.max(w/bImg.naturalWidth,h/bImg.naturalHeight),dw=bImg.naturalWidth*scale,dh=bImg.naturalHeight*scale;c.globalAlpha=.72;c.drawImage(bImg,(w-dw)/2,(h-dh)/2,dw,dh);c.globalAlpha=1}else{const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#79c9d4');g.addColorStop(.55,'#2f93a2');g.addColorStop(1,'#113f4a');c.fillStyle=g;c.fillRect(0,0,w,h)}const b=W.battle,sp=b.sp,age=(performance.now()-b.start)/1000;c.fillStyle='rgba(3,16,22,.18)';c.fillRect(0,0,w,h);c.strokeStyle='#ffffff50';c.lineWidth=3;for(let i=0;i<12;i++){const yy=h*.42+i*25+Math.sin(age*2+i)*7;c.beginPath();c.ellipse((i*147+age*35)%w,yy,80,14,0,0,Math.PI*2);c.stroke()}let x=w*.70+Math.sin(age*sp.speed)*w*.055,y=h*.43+Math.sin(age*1.8)*12,sc=Math.min(w/1100,h/680)*(sp.id==='meg'?1.65:sp.id==='whale'?1.35:sp.id==='reef'?.78:1);if(performance.now()<b.attackUntil){const q=1-(b.attackUntil-performance.now())/520;sc*=1+Math.sin(q*Math.PI)*.55;x-=Math.sin(q*Math.PI)*w*.12}drawShark(c,x,y,sp,sc,age);for(const s of b.splash){s.r+=3;s.a-=.04;c.strokeStyle=`rgba(255,255,255,${Math.max(0,s.a)})`;c.lineWidth=3;c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.stroke()}b.splash=b.splash.filter(s=>s.a>0);battleRAF=requestAnimationFrame(drawBattle)}
function drawShark(c,x,y,sp,sc,t){c.save();c.translate(x,y);c.scale(sc,sc);const tail=Math.sin(t*4*sp.speed)*.16;c.rotate(Math.sin(t*1.3)*.025);c.fillStyle=sp.color;c.strokeStyle='#27373c';c.lineWidth=3;c.beginPath();c.ellipse(0,0,185,62,0,0,Math.PI*2);c.fill();c.stroke();c.save();c.translate(-165,0);c.rotate(tail);c.beginPath();c.moveTo(0,0);c.lineTo(-88,-65);c.lineTo(-65,0);c.lineTo(-88,65);c.closePath();c.fill();c.stroke();c.restore();c.beginPath();c.moveTo(-15,-52);c.lineTo(35,-132);c.lineTo(65,-45);c.closePath();c.fill();c.beginPath();c.moveTo(10,42);c.lineTo(72,108);c.lineTo(93,34);c.closePath();c.fill();if(sp.id==='hammer'){c.fillRect(120,-54,75,30);c.beginPath();c.ellipse(157,-39,42,19,0,0,Math.PI*2);c.fill()}else{c.beginPath();c.ellipse(150,0,74,52,0,0,Math.PI*2);c.fill()}if(sp.id==='whale'){c.fillStyle='#d7edf1';for(let i=0;i<26;i++){const px=-120+(i*47)%270,py=-38+((i*31)%76);c.beginPath();c.arc(px,py,3.2,0,Math.PI*2);c.fill()}}if(sp.id==='tiger'){c.strokeStyle='#453d33';c.lineWidth=7;for(let i=-80;i<100;i+=34){c.beginPath();c.moveTo(i,-45);c.lineTo(i+18,45);c.stroke()}}c.fillStyle='#d9e1e2';c.beginPath();c.ellipse(65,25,128,27,0,0,Math.PI*2);c.fill();c.fillStyle='#02090c';c.beginPath();c.arc(152,-16,5,0,Math.PI*2);c.fill();c.strokeStyle='#263338';c.lineWidth=5;c.beginPath();c.arc(170,10,32,.2,2.5);c.stroke();if(sp.id==='meg'){c.strokeStyle='#f4f5ef';c.lineWidth=3;for(let i=0;i<6;i++){c.beginPath();c.moveTo(152+i*7,23);c.lineTo(157+i*7,34);c.stroke()}}c.restore()}
function setActions(on){['observeBtn','captureBtn','dogBtn','runBtn'].forEach(id=>$('#'+id).disabled=!on);if(W.battle?.dogUsed)$('#dogBtn').disabled=true}
function enemyHit(){const b=W.battle,sp=b.sp;let dmg=sp.power+Math.floor(Math.random()*5);if(b.shield){dmg=Math.ceil(dmg/2);b.shield=false}S.hp=Math.max(0,S.hp-dmg);$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;b.attackUntil=performance.now()+520;b.splash.push({x:W.vw*.62,y:W.vh*.46,r:20,a:.8},{x:W.vw*.72,y:W.vh*.4,r:10,a:.7},{x:W.vw*.68,y:W.vh*.52,r:16,a:.6});document.getElementById('battle').classList.remove('attack');void document.getElementById('battle').offsetWidth;document.getElementById('battle').classList.add('attack');save();if(S.hp<=0){$('#battleText').textContent='Tu es épuisé·e. Syrachi te ramène au camp de base.';setActions(false);setTimeout(()=>{S.hp=100;S.x=590;S.y=1190;closeBattle();toast('Syrachi t’a ramené au camp 🐕')},1100);return true}return false}
$('#observeBtn').onclick=()=>{const b=W.battle;if(!b)return;setActions(false);let d=17+Math.floor(Math.random()*18);if(b.sp.id==='mako')d=Math.floor(d*.72);if(b.sp.id==='whale')d=Math.floor(d*1.25);b.calm=Math.max(6,b.calm-d);$('#enemyPct').textContent=b.calm+'%';$('#enemyBar').style.width=b.calm+'%';$('#battleText').textContent=`Tu observes ${b.sp.name.toLowerCase()} : son comportement devient plus prévisible.`;setTimeout(()=>{if(b.sp.id==='whale'&&Math.random()<.55){$('#battleText').textContent+=' Il reste paisible.';setActions(true)}else if(!enemyHit()){$('#battleText').textContent+=' Il riposte !';setActions(true)}},700)};
$('#dogBtn').onclick=()=>{const b=W.battle;if(!b||b.dogUsed)return;b.shield=true;b.dogUsed=true;$('#battleText').textContent='Syrachi s’avance et aboie : le requin détourne brièvement son attention.';$('#dogBtn').disabled=true};
$('#captureBtn').onclick=()=>{const b=W.battle;if(!b)return;if(S.balls<=0){$('#battleText').textContent='Plus de Pokéballs. Retourne au camp.';return}S.balls--;$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;save();setActions(false);const fx=$('#ballFx');fx.classList.remove('go');void fx.offsetWidth;fx.classList.add('go');const chance=Math.min(.94,b.sp.base+(100-b.calm)/125+(b.dogUsed?.04:0));$('#battleText').textContent='Pokéball lancée…';setTimeout(()=>{if(Math.random()<chance){S.caught[b.sp.id]=(S.caught[b.sp.id]||0)+1;S.seen[b.sp.id]=true;save();const f=$('#captureFlash');f.classList.remove('go');void f.offsetWidth;f.classList.add('go');const battleEl=document.getElementById('battle');battleEl.classList.remove('captureSuccess');void battleEl.offsetWidth;battleEl.classList.add('captureSuccess');$('#battleText').textContent=`Capture réussie ! ${b.sp.name} rejoint ton SharkDex.`;setTimeout(()=>{closeBattle();refresh();toast(`${b.sp.name} capturé !`)},1050)}else{$('#battleText').textContent='La Pokéball s’ouvre : le requin se libère !';if(!enemyHit())setActions(true)}},950)};
$('#runBtn').onclick=()=>{const b=W.battle;if(!b)return;setActions(false);const chance=Math.max(.55,.92-(b.sp.speed-.6)*.22);if(Math.random()<chance){$('#battleText').textContent='Vous reculez prudemment avec Syrachi.';setTimeout(closeBattle,600)}else{$('#battleText').textContent='Impossible de reculer : le requin coupe votre trajectoire !';setTimeout(()=>{if(!enemyHit())setActions(true)},500)}};
function closeBattle(){cancelAnimationFrame(battleRAF);W.battle=null;$('#battle').classList.add('hidden');refresh();save();W.nextFin=performance.now()+5000}
function renderDex(){const grid=$('#dexGrid');grid.innerHTML='';species.forEach(sp=>{const seen=S.seen[sp.id]||S.caught[sp.id],n=S.caught[sp.id]||0,d=document.createElement('button');d.className='dexCard'+(seen?'':' lock');d.innerHTML=`<div class="dexIcon">${seen?'🦈':'❔'}</div><div><b>${seen?sp.name:'Espèce inconnue'}</b><small>${seen?`${sp.rarity} • capturé x${n}`:'Non découverte'}</small></div>`;d.onclick=()=>showDex(sp,seen,n);grid.appendChild(d)})}
function showDex(sp,seen,n){$('#dexShark').textContent=seen?'🦈':'❔';$('#dexName').textContent=seen?sp.name:'Espèce inconnue';$('#dexInfo').textContent=seen?`${sp.rarity} • ${sp.temper} • capturé x${n}. ${sp.desc}`:'Explore les zones côtières et observe les nageoires dans l’eau pour découvrir cette espèce.'}
$('#dexBtn').onclick=()=>{renderDex();$('#dex').classList.remove('hidden')};$('#closeDex').onclick=()=>$('#dex').classList.add('hidden');
addEventListener('keydown',e=>W.keys[e.key]=1);addEventListener('keyup',e=>W.keys[e.key]=0);$$('.dpad button').forEach(b=>{const d=b.dataset.dir;b.onpointerdown=e=>{e.preventDefault();W.touch[d]=1};b.onpointerup=b.onpointercancel=b.onpointerout=e=>{e.preventDefault();W.touch[d]=0}});refresh();drawMap();
})();