(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#world'),ctx=canvas.getContext('2d');
const KEY='sharkquest-v52';let S={char:null,hp:100,balls:6,caught:0,x:610,y:960};try{Object.assign(S,JSON.parse(localStorage.getItem(KEY))||{})}catch{};const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const world={w:2200,h:1500,touch:{},cam:{x:0,y:0},last:performance.now(),rollAt:0,battle:null};const keys={};
const lagoons=[{x:360,y:380,w:470,h:300},{x:1280,y:340,w:520,h:310},{x:760,y:890,w:690,h:260}],rocks=[{x:630,y:700,r:55},{x:1140,y:620,r:48},{x:1650,y:850,r:65},{x:500,y:1120,r:52}],camp={x:270,y:1080,w:280,h:200};
let VIS={justine:'',guillaume:'',syrachi:'',battle:''};const portrait=n=>n==='Guillaume'?VIS.guillaume:VIS.justine,battleImg=n=>VIS.battle;

async function b64Asset(path,type='image/webp'){const t=await fetch(path,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(path);return r.text()});const b=atob(t.trim()),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return URL.createObjectURL(new Blob([u],{type}))}
async function loadVisuals(){try{const [j,g,d]=await Promise.all([b64Asset('../assets/justine.b64'),b64Asset('../assets/guillaume.b64'),b64Asset('../assets/syrachi.b64')]);VIS.justine=j;VIS.guillaume=g;VIS.syrachi=d;$('#justineCardImg').src=j;$('#guillaumeCardImg').src=g;$('#syrachiCardImg').src=d;$('#hudDog').src=d;}catch(e){console.warn('portraits',e)}try{VIS.battle=await b64Asset('../assets/battle_justine.b64');document.querySelector('.start-bg').style.backgroundImage=`linear-gradient(110deg,#06151cf2 0 38%,#0a2735b8 62%,#0006),url('${VIS.battle}')`;}catch(e){console.warn('battle visual fallback',e)}}
loadVisuals();

function fit(){const d=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);world.viewW=w;world.viewH=h;}
addEventListener('resize',fit);fit();
function roundRect(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawWorld(){const W=world.viewW,H=world.viewH;ctx.clearRect(0,0,W,H);world.cam.x=Math.max(0,Math.min(world.w-W,S.x-W/2));world.cam.y=Math.max(0,Math.min(world.h-H,S.y-H/2));ctx.save();ctx.translate(-world.cam.x,-world.cam.y);
 ctx.fillStyle='#39a3b2';ctx.fillRect(0,0,world.w,world.h);ctx.strokeStyle='#ffffff22';ctx.lineWidth=2;for(let y=20;y<world.h;y+=55)for(let x=(y%110?0:35);x<world.w;x+=90){ctx.beginPath();ctx.ellipse(x,y,30,7,0,0,Math.PI*2);ctx.stroke()}
 roundRect(120,110,1960,1280,180,'#e4c47e');roundRect(245,245,1710,1010,125,'#72aa58');roundRect(300,300,1600,900,105,'#85bd63');
 lagoons.forEach((l,i)=>{roundRect(l.x,l.y,l.w,l.h,100,'#49b4c2');roundRect(l.x+22,l.y+20,l.w-44,l.h-40,82,'#71cad2');ctx.strokeStyle='#3d7137';ctx.lineWidth=4;for(let x=l.x+18;x<l.x+l.w-15;x+=28){ctx.beginPath();ctx.moveTo(x,l.y+l.h-8);ctx.lineTo(x+7,l.y+45+(x%3)*7);ctx.stroke()}});
 roundRect(430,1180,1250,105,42,'#d4b36f');roundRect(1040,610,120,600,42,'#d4b36f');roundRect(720,260,1050,80,32,'#d4b36f');
 roundRect(camp.x,camp.y,camp.w,camp.h,24,'#735139');ctx.fillStyle='#b95448';ctx.beginPath();ctx.moveTo(camp.x-20,camp.y+25);ctx.lineTo(camp.x+camp.w/2,camp.y-95);ctx.lineTo(camp.x+camp.w+20,camp.y+25);ctx.fill();
 ctx.fillStyle='#704d31';ctx.fillRect(1790,655,300,75);for(let i=0;i<7;i++)ctx.fillRect(1805+i*43,610,16,155);
 rocks.forEach(r=>{ctx.fillStyle='#66787d';ctx.beginPath();ctx.ellipse(r.x,r.y,r.r,r.r*.7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#91a0a2';ctx.beginPath();ctx.ellipse(r.x-12,r.y-12,r.r*.42,r.r*.22,-.4,0,Math.PI*2);ctx.fill()});
 ctx.fillStyle='#19333a';ctx.font='700 15px system-ui';ctx.fillText('LAGON TURQUOISE',390,365);ctx.fillText('LAGON NORD',1340,325);ctx.fillText('LAGON DES ROSEAUX',900,875);ctx.fillText('CAMP DE BASE',295,1315);ctx.fillText('PONTON',1830,770);
 drawDog(S.x-38,S.y+42);drawPlayer(S.x,S.y,S.char);
 ctx.restore();}
function drawPlayer(x,y,n){ctx.save();ctx.translate(x,y);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,28,27,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=n==='Justine'?'#3c3432':'#59696d';ctx.beginPath();ctx.roundRect(-22,-18,44,60,15);ctx.fill();ctx.fillStyle='#d7a184';ctx.beginPath();ctx.arc(0,-35,18,0,Math.PI*2);ctx.fill();ctx.fillStyle=n==='Justine'?'#5b3427':'#251d1b';ctx.beginPath();ctx.arc(0,-41,20,Math.PI,Math.PI*2);ctx.fill();if(n==='Justine'){ctx.strokeStyle='#5b3427';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-16,-39);ctx.quadraticCurveTo(-28,-5,-18,28);ctx.moveTo(16,-39);ctx.quadraticCurveTo(28,-5,18,28);ctx.stroke()}ctx.fillStyle='#463828';ctx.fillRect(-17,-15,34,39);ctx.restore()}
function drawDog(x,y){ctx.save();ctx.translate(x,y);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(0,22,25,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#11181b';ctx.beginPath();ctx.ellipse(0,0,38,27,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#edf2f2';ctx.beginPath();ctx.ellipse(0,-4,12,25,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#11181b';ctx.beginPath();ctx.moveTo(-14,-16);ctx.lineTo(-22,-34);ctx.lineTo(-4,-20);ctx.fill();ctx.beginPath();ctx.moveTo(14,-16);ctx.lineTo(22,-34);ctx.lineTo(4,-20);ctx.fill();ctx.restore()}
function blocked(x,y){if(x<170||y<170||x>2030||y>1330)return true;if(lagoons.some(l=>x>l.x+40&&x<l.x+l.w-40&&y>l.y+40&&y<l.y+l.h-40))return true;if(rocks.some(r=>Math.hypot(x-r.x,y-r.y)<r.r+25))return true;return false}
function nearLagoon(){return lagoons.some(l=>S.x>l.x-85&&S.x<l.x+l.w+85&&S.y>l.y-85&&S.y<l.y+l.h+85)}
function update(dt){if($('#game').classList.contains('hidden')||world.battle)return;let dx=0,dy=0;if(keys.ArrowLeft||keys.a||world.touch.left)dx--;if(keys.ArrowRight||keys.d||world.touch.right)dx++;if(keys.ArrowUp||keys.w||world.touch.up)dy--;if(keys.ArrowDown||keys.s||world.touch.down)dy++;if(dx&&dy){dx*=.707;dy*=.707}const sp=235,nx=S.x+dx*sp*dt,ny=S.y+dy*sp*dt;if(!blocked(nx,S.y))S.x=nx;if(!blocked(S.x,ny))S.y=ny;if(dx||dy){if(nearLagoon()&&performance.now()>world.rollAt){world.rollAt=performance.now()+900;if(Math.random()<.18)startBattle()}if(S.x>camp.x-35&&S.x<camp.x+camp.w+35&&S.y>camp.y-35&&S.y<camp.y+camp.h+35){if(S.hp<100||S.balls<6){S.hp=100;S.balls=Math.max(S.balls,6);refresh();save();toast('Camp : énergie et Pokéballs restaurées')}}}drawWorld()}
function loop(t){const dt=Math.min(.035,(t-world.last)/1000);world.last=t;update(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function refresh(){const p=portrait(S.char||'Justine');$('#hudPortrait').src=p;$('#hudName').textContent=S.char||'Justine';$('#hp').textContent=S.hp;$('#balls').textContent=S.balls;$('#count').textContent=S.caught;$('#quest').textContent=S.caught?'Mission accomplie : Grand requin blanc capturé. Continue à explorer.':'Mission : approche un lagon et capture le Grand requin blanc.'}
let toastTimer;function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1700)}
function startGame(){if(!S.char)return;$('#start').classList.add('hidden');$('#game').classList.remove('hidden');refresh();drawWorld();save()}
$$('.char-card').forEach(b=>b.addEventListener('click',()=>{S.char=b.dataset.char;$$('.char-card').forEach(x=>x.classList.toggle('selected',x===b));$('#playBtn').disabled=false;$('#playBtn').textContent='Commencer avec '+S.char;if(VIS.battle)document.querySelector('.start-bg').style.backgroundImage=`linear-gradient(110deg,#06151cf2 0 38%,#0a2735b8 62%,#0006),url('${VIS.battle}')`}));$('#playBtn').onclick=startGame;if(S.char){$('#resumeBtn').classList.remove('hidden');$('#resumeBtn').onclick=startGame;const b=$(`.char-card[data-char="${S.char}"]`);if(b){b.classList.add('selected');$('#playBtn').disabled=false;$('#playBtn').textContent='Nouvelle partie avec '+S.char}}
function startBattle(){world.battle={hp:100,shield:false,dog:false};$('#battleImg').src=VIS.battle||'';$('#battlePortrait').src=portrait(S.char)||'';$('#battleName').textContent=S.char+' + Syrachi';$('#enemyPct').textContent='100%';$('#enemyBar').style.width='100%';$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;$('#battleText').textContent='Un Grand requin blanc surgit du lagon ! Observe-le pour augmenter tes chances de capture.';$('#battle').classList.remove('hidden');setActions(true)}
function setActions(on){['observeBtn','captureBtn','dogBtn','runBtn'].forEach(id=>$('#'+id).disabled=!on);if(world.battle?.dog)$('#dogBtn').disabled=true}
function enemyHit(){let d=10+Math.floor(Math.random()*7);if(world.battle.shield){d=Math.ceil(d/2);world.battle.shield=false}S.hp=Math.max(0,S.hp-d);$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;save();if(S.hp<=0){$('#battleText').textContent='Tu es épuisé·e. Syrachi te ramène au camp.';setActions(false);setTimeout(()=>{S.hp=100;S.x=570;S.y=1070;closeBattle();toast('Syrachi t’a ramené au camp 🐕')},1000);return true}return false}
$('#observeBtn').onclick=()=>{if(!world.battle)return;setActions(false);const d=18+Math.floor(Math.random()*18);world.battle.hp=Math.max(10,world.battle.hp-d);$('#enemyPct').textContent=world.battle.hp+'%';$('#enemyBar').style.width=world.battle.hp+'%';$('#battleText').textContent=`Tu observes les mouvements du requin. Il se fatigue : -${d}.`;setTimeout(()=>{if(!enemyHit()){document.querySelector('.battle-scene').animate([{transform:'translateX(0)'},{transform:'translateX(-7px)'},{transform:'translateX(7px)'},{transform:'translateX(0)'}],{duration:260});$('#battleText').textContent+=' Il riposte !';setActions(true)}},650)};
$('#dogBtn').onclick=()=>{if(!world.battle||world.battle.dog)return;world.battle.shield=true;world.battle.dog=true;$('#battleText').textContent='Syrachi aboie et détourne son attention. La prochaine riposte sera réduite.';$('#dogBtn').disabled=true};
$('#captureBtn').onclick=()=>{if(!world.battle)return;if(S.balls<=0){$('#battleText').textContent='Plus de Pokéballs. Retourne au camp.';return}S.balls--;$('#battleStats').textContent=`❤️ ${S.hp} • 🔴 ${S.balls}`;save();setActions(false);const fx=$('#ballFx');fx.classList.remove('go');void fx.offsetWidth;fx.classList.add('go');const chance=Math.min(.92,.32+(100-world.battle.hp)/120);$('#battleText').textContent='Tu lances une Pokéball…';setTimeout(()=>{if(Math.random()<chance){S.caught=1;save();$('#battleText').textContent='Capture réussie ! Grand requin blanc ajouté au SharkDex.';setTimeout(()=>{closeBattle();refresh();toast('Grand requin blanc capturé ! 🦈')},900)}else{$('#battleText').textContent='Il se libère !';if(!enemyHit())setActions(true)}},900)};
$('#runBtn').onclick=()=>{if(!world.battle)return;setActions(false);if(Math.random()<.86){$('#battleText').textContent='Vous reculez prudemment avec Syrachi.';setTimeout(closeBattle,550)}else{$('#battleText').textContent='Impossible de reculer maintenant !';setTimeout(()=>{if(!enemyHit())setActions(true)},500)}};
function closeBattle(){world.battle=null;$('#battle').classList.add('hidden');refresh();save()}
$('#dexBtn').onclick=()=>{if(S.caught){$('#dexName').textContent='Grand requin blanc';$('#dexInfo').textContent='Prédateur côtier puissant. Dans SharkQuest, tu l’as observé puis capturé près des lagons de l’île.'}else{$('#dexName').textContent='???';$('#dexInfo').textContent='Aucune capture enregistrée. Approche les lagons pour provoquer une rencontre.'}$('#dex').classList.remove('hidden')};$('#closeDex').onclick=()=>$('#dex').classList.add('hidden');
addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);$$('.dpad button').forEach(b=>{const d=b.dataset.dir;['pointerdown','touchstart'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();world.touch[d]=1},{passive:false}));['pointerup','pointercancel','pointerout','touchend'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();world.touch[d]=0},{passive:false}))});
refresh();
})();
